<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>22&nbsp; Modèle Sulfaco — Attaque Sulfatique Interne/Externe du Béton – Bil</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Sulfuricem_model.html" rel="next">
<link href="./Chloricem_model.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-23fd4533d2f2b834c87e926c7060fcb1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-ddf985e630d529526cf0a290dcd10a29.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-23fd4533d2f2b834c87e926c7060fcb1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e30f798487214bd1bc8412a3dcfaebc7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-f5b556d071665e9458de864191fbc25a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-e30f798487214bd1bc8412a3dcfaebc7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Bil</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/dangla/bil" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Fick_model.html">Exemples — Durabilité &amp; Chimie</a></li><li class="breadcrumb-item"><a href="./Sulfaco_model.html"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Modèle Sulfaco — Attaque Sulfatique Interne/Externe du Béton</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bil — Documentation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lancer_calcul.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lancer un calcul avec Bil</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fonctionnement_bil.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Architecture et fonctionnement de Bil</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Exemples — Écoulement</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M1_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modèle M1 — Équation de Richards (Écoulement liquide 1D)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M2_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modèle M2 — Écoulement Diphasique L/G (Liquide-Gaz)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M5_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modèle M5 — Transferts couplés eau–air en milieu poreux non saturé (isotherme 1D)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M10-1_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modèle M10 — Équation de Richards : drainage d’une colonne de billes sous gravité (1D)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M10-2_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Modèle M10 — Équation de Richards : drainage d’une colonne de billes sous gravité (2D)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Richards-2d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Richards-2d — Drainage d’une colonne de billes</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Exemples — Mécanique</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Elast0_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Modèle Elast0 — Élasticité Linéaire Isotope (Géométrie Axisymétrique)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Elasd_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modèle Elasd — Élasticité avec Endommagement Isotrope (Quasi-statique)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Plast_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Modèle Plast — Élasto-plasticité avec critère de Drucker-Prager (ou Cam-Clay)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./BBM_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Modèle BBM — Barcelona Basic Model pour sols non saturés (2D axisymétrique)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Poroplast_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modèle Poroplast — Poroélastoplasticité avec Écrouissage (Forage en Milieu Poreux Saturé)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Exemples — Poromécanique</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M7_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Modèle M7 — Poroélasticité Saturée/Non-Saturée (Consolidation de Biot)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M7-1_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Modèle M7 — Poroélasticité non saturée de Biot · Cas test M7-1 : Barrage de Ternay</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Exemples — Gel</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Frostaco_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Modèle Frostaco — Action du gel dans le béton</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Frostaco3d_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Modèle Frostaco3D — Action du gel dans le béton en 3D (Couplage Poromécanique Complet)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Exemples — Durabilité &amp; Chimie</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Fick_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modèle Fick — Seconde loi de Fick (Diffusion de soluté)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Duracem_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Modèle Duracem — Durabilité des matériaux cimentaires : carbonatation et ingression de chlorures (1D)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chloricem_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Modèle Chloricem — Durabilité des matériaux cimentaires : pénétration des chlorures (1D)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Sulfaco_model.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Modèle Sulfaco — Attaque Sulfatique Interne/Externe du Béton</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Sulfuricem_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Modèle Sulfuricem — Attaque à l’acide sulfurique des matériaux cimentaires</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Sulfaconew_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modèle Sulfaconew — Refactorisation C++ du modèle Sulfaco avec l’interface MaterialPointMethod</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SulfacoESA3d_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Modèle SulfacoESA3d — Attaque Sulfatique Externe avec Endommagement Mécanique 3D</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Exemples — Transferts couplés</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DWS1_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Modèle DWS1 — Séchage et Mouillage avec Sel (isotherme 1D)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Yuan1_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modèle Yuan1 — Attaque au Sulfure d’Hydrogène (H₂S) du béton</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Shen_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Modèle Shen — Carbonatation du béton au CO₂ supercritique</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./usoil_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Modèle usoil — Mécanique des Sols Non-Saturés (2019)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Exemples — Spécialisés</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MechaMic_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Modèle MechaMic — FEM² Multiscale Mechanics (2017)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./M2_VoronoiFVM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">M2 — Écoulement diphasique liquide-gaz 1D : portage Bil → Julia/VoronoiFVM</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sur cette page</h2>
   
  <ul>
  <li><a href="#table-des-matières" id="toc-table-des-matières" class="nav-link active" data-scroll-target="#table-des-matières"><span class="header-section-number">22.1</span> Table des matières</a></li>
  <li><a href="#contexte-et-objectif" id="toc-contexte-et-objectif" class="nav-link" data-scroll-target="#contexte-et-objectif"><span class="header-section-number">22.2</span> 1. Contexte et objectif</a></li>
  <li><a href="#hypothèses" id="toc-hypothèses" class="nav-link" data-scroll-target="#hypothèses"><span class="header-section-number">22.3</span> 2. Hypothèses</a></li>
  <li><a href="#variables-et-notation" id="toc-variables-et-notation" class="nav-link" data-scroll-target="#variables-et-notation"><span class="header-section-number">22.4</span> 3. Variables et notation</a>
  <ul class="collapse">
  <li><a href="#inconnues-primaires-6-équations" id="toc-inconnues-primaires-6-équations" class="nav-link" data-scroll-target="#inconnues-primaires-6-équations"><span class="header-section-number">22.4.1</span> Inconnues primaires (6 équations)</a></li>
  <li><a href="#principales-variables-secondaires-calculées" id="toc-principales-variables-secondaires-calculées" class="nav-link" data-scroll-target="#principales-variables-secondaires-calculées"><span class="header-section-number">22.4.2</span> Principales variables secondaires calculées</a></li>
  </ul></li>
  <li><a href="#modèle-mathématique" id="toc-modèle-mathématique" class="nav-link" data-scroll-target="#modèle-mathématique"><span class="header-section-number">22.5</span> 4. Modèle mathématique</a>
  <ul class="collapse">
  <li><a href="#équations-de-conservation" id="toc-équations-de-conservation" class="nav-link" data-scroll-target="#équations-de-conservation"><span class="header-section-number">22.5.1</span> 4.1 Équations de conservation</a></li>
  <li><a href="#chimie-de-la-solution-interstitielle" id="toc-chimie-de-la-solution-interstitielle" class="nav-link" data-scroll-target="#chimie-de-la-solution-interstitielle"><span class="header-section-number">22.5.2</span> 4.2 Chimie de la solution interstitielle</a></li>
  <li><a href="#réactions-avec-les-phases-solides" id="toc-réactions-avec-les-phases-solides" class="nav-link" data-scroll-target="#réactions-avec-les-phases-solides"><span class="header-section-number">22.5.3</span> 4.3 Réactions avec les phases solides</a></li>
  <li><a href="#pression-de-cristallisation-et-endommagement" id="toc-pression-de-cristallisation-et-endommagement" class="nav-link" data-scroll-target="#pression-de-cristallisation-et-endommagement"><span class="header-section-number">22.5.4</span> 4.4 Pression de cristallisation et endommagement</a></li>
  <li><a href="#loi-de-transport-diffusion-ionique" id="toc-loi-de-transport-diffusion-ionique" class="nav-link" data-scroll-target="#loi-de-transport-diffusion-ionique"><span class="header-section-number">22.5.5</span> 4.5 Loi de transport (diffusion ionique)</a></li>
  </ul></li>
  <li><a href="#conditions-aux-limites-et-initiales" id="toc-conditions-aux-limites-et-initiales" class="nav-link" data-scroll-target="#conditions-aux-limites-et-initiales"><span class="header-section-number">22.6</span> 5. Conditions aux limites et initiales</a>
  <ul class="collapse">
  <li><a href="#conditions-initiales" id="toc-conditions-initiales" class="nav-link" data-scroll-target="#conditions-initiales"><span class="header-section-number">22.6.1</span> Conditions initiales</a></li>
  <li><a href="#conditions-aux-limites" id="toc-conditions-aux-limites" class="nav-link" data-scroll-target="#conditions-aux-limites"><span class="header-section-number">22.6.2</span> Conditions aux limites</a></li>
  </ul></li>
  <li><a href="#cas-test-attaque-sulfatique-dun-échantillon-de-béton-basesulfaco" id="toc-cas-test-attaque-sulfatique-dun-échantillon-de-béton-basesulfaco" class="nav-link" data-scroll-target="#cas-test-attaque-sulfatique-dun-échantillon-de-béton-basesulfaco"><span class="header-section-number">22.7</span> 6. Cas test : Attaque sulfatique d’un échantillon de béton (<code>base/Sulfaco/</code>)</a>
  <ul class="collapse">
  <li><a href="#géométrie" id="toc-géométrie" class="nav-link" data-scroll-target="#géométrie"><span class="header-section-number">22.7.1</span> Géométrie</a></li>
  <li><a href="#scénario-simulé" id="toc-scénario-simulé" class="nav-link" data-scroll-target="#scénario-simulé"><span class="header-section-number">22.7.2</span> Scénario simulé</a></li>
  <li><a href="#résultats-attendus-sorties-.gp" id="toc-résultats-attendus-sorties-.gp" class="nav-link" data-scroll-target="#résultats-attendus-sorties-.gp"><span class="header-section-number">22.7.3</span> Résultats attendus (sorties <code>.gp</code>)</a></li>
  </ul></li>
  <li><a href="#paramétrage-matériel-du-modèle" id="toc-paramétrage-matériel-du-modèle" class="nav-link" data-scroll-target="#paramétrage-matériel-du-modèle"><span class="header-section-number">22.8</span> 7. Paramétrage matériel du modèle</a></li>
  <li><a href="#description-pas-à-pas-des-fichiers-dentrée" id="toc-description-pas-à-pas-des-fichiers-dentrée" class="nav-link" data-scroll-target="#description-pas-à-pas-des-fichiers-dentrée"><span class="header-section-number">22.9</span> 8. Description pas-à-pas des fichiers d’entrée</a>
  <ul class="collapse">
  <li><a href="#système-dunités-units" id="toc-système-dunités-units" class="nav-link" data-scroll-target="#système-dunités-units"><span class="header-section-number">22.9.1</span> 8.1 Système d’unités (<code>Units</code>)</a></li>
  <li><a href="#géométrie-et-maillage-geometry-mesh" id="toc-géométrie-et-maillage-geometry-mesh" class="nav-link" data-scroll-target="#géométrie-et-maillage-geometry-mesh"><span class="header-section-number">22.9.2</span> 8.2 Géométrie et maillage (<code>Geometry</code>, <code>Mesh</code>)</a></li>
  <li><a href="#matériau-material" id="toc-matériau-material" class="nav-link" data-scroll-target="#matériau-material"><span class="header-section-number">22.9.3</span> 8.3 Matériau (<code>Material</code>)</a></li>
  <li><a href="#champs-fields" id="toc-champs-fields" class="nav-link" data-scroll-target="#champs-fields"><span class="header-section-number">22.9.4</span> 8.4 Champs (<code>Fields</code>)</a></li>
  <li><a href="#initialisation-initialization" id="toc-initialisation-initialization" class="nav-link" data-scroll-target="#initialisation-initialization"><span class="header-section-number">22.9.5</span> 8.5 Initialisation (<code>Initialization</code>)</a></li>
  <li><a href="#fonctions-temporelles-functions" id="toc-fonctions-temporelles-functions" class="nav-link" data-scroll-target="#fonctions-temporelles-functions"><span class="header-section-number">22.9.6</span> 8.6 Fonctions temporelles (<code>Functions</code>)</a></li>
  <li><a href="#conditions-aux-limites-boundary-conditions" id="toc-conditions-aux-limites-boundary-conditions" class="nav-link" data-scroll-target="#conditions-aux-limites-boundary-conditions"><span class="header-section-number">22.9.7</span> 8.7 Conditions aux limites (<code>Boundary Conditions</code>)</a></li>
  <li><a href="#points-dobservation-points" id="toc-points-dobservation-points" class="nav-link" data-scroll-target="#points-dobservation-points"><span class="header-section-number">22.9.8</span> 8.8 Points d’observation (<code>Points</code>)</a></li>
  <li><a href="#fenêtre-temporelle-et-critères-de-convergence" id="toc-fenêtre-temporelle-et-critères-de-convergence" class="nav-link" data-scroll-target="#fenêtre-temporelle-et-critères-de-convergence"><span class="header-section-number">22.9.9</span> 8.9 Fenêtre temporelle et critères de convergence</a></li>
  </ul></li>
  <li><a href="#références-bibliographiques" id="toc-références-bibliographiques" class="nav-link" data-scroll-target="#références-bibliographiques"><span class="header-section-number">22.10</span> 9. Références bibliographiques</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dangla/bil/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Fick_model.html">Exemples — Durabilité &amp; Chimie</a></li><li class="breadcrumb-item"><a href="./Sulfaco_model.html"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Modèle Sulfaco — Attaque Sulfatique Interne/Externe du Béton</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Modèle Sulfaco — Attaque Sulfatique Interne/Externe du Béton</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Fichiers sources :</strong> <code>src/Models/ModelFiles/Sulfaco.c</code> · <code>base/Sulfaco/Sulfaco</code></p>
<p><strong>Auteurs du modèle :</strong> Gu, Dangla (Université Gustave Eiffel) <strong>Titre interne :</strong> <em>“Internal/External sulfate attack of concrete (2017)”</em></p>
</blockquote>
<hr>
<section id="table-des-matières" class="level2" data-number="22.1">
<h2 data-number="22.1" class="anchored" data-anchor-id="table-des-matières"><span class="header-section-number">22.1</span> Table des matières</h2>
<ol type="1">
<li><a href="#1-contexte-et-objectif">Contexte et objectif</a></li>
<li><a href="#2-hypothèses">Hypothèses</a></li>
<li><a href="#3-variables-et-notation">Variables et notation</a></li>
<li><a href="#4-modèle-mathématique">Modèle mathématique</a>
<ul>
<li>4.1 <a href="#41-équations-de-conservation">Équations de conservation</a></li>
<li>4.2 <a href="#42-chimie-de-la-solution-interstitielle">Chimie de la solution interstitielle</a></li>
<li>4.3 <a href="#43-réactions-avec-les-phases-solides">Réactions avec les phases solides</a></li>
<li>4.4 <a href="#44-pression-de-cristallisation-et-endommagement">Pression de cristallisation et endommagement</a></li>
<li>4.5 <a href="#45-loi-de-transport-diffusion-ionique">Loi de transport (diffusion ionique)</a></li>
</ul></li>
<li><a href="#5-conditions-aux-limites-et-initiales">Conditions aux limites et initiales</a></li>
<li><a href="#6-cas-test--attaque-sulfatique-dun-échantillon-de-béton-basesulfaco">Cas test : Attaque sulfatique d’un échantillon de béton (<code>base/Sulfaco/</code>)</a></li>
<li><a href="#7-paramétrage-matériel-du-modèle">Paramétrage matériel du modèle</a></li>
<li><a href="#8-description-pas-à-pas-des-fichiers-dentrée">Description pas-à-pas des fichiers d’entrée</a></li>
<li><a href="#9-références-bibliographiques">Références bibliographiques</a></li>
</ol>
<hr>
</section>
<section id="contexte-et-objectif" class="level2" data-number="22.2">
<h2 data-number="22.2" class="anchored" data-anchor-id="contexte-et-objectif"><span class="header-section-number">22.2</span> 1. Contexte et objectif</h2>
<p>Le modèle <strong>Sulfaco</strong> simule la <strong>dégradation chimique du béton armé par attaque sulfatique</strong> (interne ou externe). Ce phénomène de durabilité est l’une des principales causes de détérioration à long terme des infrastructures en béton (ouvrages d’art, fondations, tunnels en terrain gypseux).</p>
<p>L’attaque sulfatique se produit lorsque des ions sulfate (<span class="math inline">\(\text{SO}_4^{2-}\)</span>) pénètrent dans la pâte de ciment durcie (attaque externe) ou sont libérés par des agrégats sulfatés (attaque interne). Ces ions réagissent avec les phases solides alumineuses du ciment hydraté pour former de l’<strong>ettringite secondaire</strong> (<span class="math inline">\(\text{AFt} = \text{C}_6\text{AS}_3\text{H}_{32}\)</span>). La formation d’ettringite en milieu confiné génère une <strong>pression de cristallisation</strong> qui excède la résistance à la traction du béton, provoquant fissuration et délaminage.</p>
<pre class="mermaid"><code>graph TD
    A["Ions SO₄²⁻ en solution&lt;br&gt;(apport externe ou interne)"] --&gt; B("Chimie de la solution de pores&lt;br&gt;Équilibre acido-basique, complexes ioniques")
    B --&gt;|Sursaturation| C["Formation de Gypse (CSH₂)&lt;br&gt;et d'Ettringite (AFt)"]
    B --&gt;|Dissolution| D["Dissolution de Portlandite (CH)&lt;br&gt;et C3AH6"]
    C --&gt; E("Variation de porosité ΔΦ&lt;br&gt;Fermeture des pores")
    E --&gt; F["Pression de cristallisation P_c&lt;br&gt;(si AFt en milieu confiné)"]
    F --&gt; G["Endommagement mécanique D(ε)"]
    G --&gt;|Ouverture de microfissures| E
    E --&gt; H["Transport ionique&lt;br&gt;(diffusion + migration électrique)"]
    H --&gt; B</code></pre>
<hr>
</section>
<section id="hypothèses" class="level2" data-number="22.3">
<h2 data-number="22.3" class="anchored" data-anchor-id="hypothèses"><span class="header-section-number">22.3</span> 2. Hypothèses</h2>
<ol type="1">
<li><strong>Isotherme</strong> : La température est fixée à <span class="math inline">\(T = 293\,\text{K}\)</span> (<span class="math inline">\(20°\text{C}\)</span>). Les constantes d’équilibre thermodynamique sont évaluées à cette température.</li>
<li><strong>Milieu poreux saturé</strong> : La solution de pores occupe l’ensemble de la porosité (pas de phase gazeuse). La saturation <span class="math inline">\(S_r\)</span> est décrite par une courbe tabulée en fonction du rayon de pore <span class="math inline">\(r\)</span>.</li>
<li><strong>Cinétique de dissolution/précipitation</strong> : Les réactions des phases solides (CSH₂, AFt, AFm, C₃AH₆) sont pilotées par des lois cinétiques du premier ordre en écart à la sursaturation, avec des taux <span class="math inline">\(R_x\)</span> (mol/L/s). La portlandite (CH) et l’ettringite (AFt à l’équilibre) obéissent à un bilan de matière direct.</li>
<li><strong>Électroneutralité</strong> : La charge électrique totale de la solution est nulle. Cette contrainte ferme le système : elle définit la concentration en <span class="math inline">\(\text{OH}^-\)</span> à partir des autres ions.</li>
<li><strong>Pression de cristallisation</strong> : La pression exercée par un cristal d’AFt en croissance dans un pore de rayon <span class="math inline">\(r\)</span> est donnée par la thermodynamique de Laplace (équation de Kelvin-Thomson).</li>
<li><strong>Endommagement uniaxial</strong> : Une déformation de gonflement <span class="math inline">\(\varepsilon\)</span> est calculée à partir des variations de porosité. Quand <span class="math inline">\(\varepsilon\)</span> dépasse le seuil <span class="math inline">\(\varepsilon_0\)</span>, une loi d’endommagement exponentielle réduit la rigidité effective.</li>
<li><strong>Diffusion de Nernst-Planck</strong> : Le transport ionique suit la loi de diffusion couplée électro-chimique, incluant la migration sous champ électrique interne (potentiel de Donnan/diffusion <span class="math inline">\(\psi\)</span>).</li>
</ol>
<hr>
</section>
<section id="variables-et-notation" class="level2" data-number="22.4">
<h2 data-number="22.4" class="anchored" data-anchor-id="variables-et-notation"><span class="header-section-number">22.4</span> 3. Variables et notation</h2>
<section id="inconnues-primaires-6-équations" class="level3" data-number="22.4.1">
<h3 data-number="22.4.1" class="anchored" data-anchor-id="inconnues-primaires-6-équations"><span class="header-section-number">22.4.1</span> Inconnues primaires (6 équations)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Symbole</th>
<th>Signification</th>
<th>Interne BIL</th>
<th>Inconnue BIL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\log c_{\text{SO}_4}\)</span></td>
<td>Log₁₀ de la concentration en sulfate</td>
<td><code>E_Sulfur</code></td>
<td><code>logc_so4</code></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\psi\)</span></td>
<td>Potentiel électrique diffus (V)</td>
<td><code>E_charge</code></td>
<td><code>psi</code></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(z_\text{Ca}\)</span></td>
<td>Quantité normalisée de calcium solide (CH)</td>
<td><code>E_Calcium</code></td>
<td><code>z_ca</code></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\log c_\text{K}\)</span></td>
<td>Log₁₀ de la concentration en potassium</td>
<td><code>E_Potassium</code></td>
<td><code>logc_k</code></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(z_\text{Al}\)</span></td>
<td>Quantité normalisée d’aluminium solide (AH₃)</td>
<td><code>E_Aluminium</code></td>
<td><code>z_al</code></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\log c_\text{OH}\)</span></td>
<td>Log₁₀ de la concentration en hydroxyle</td>
<td><code>E_eneutral</code></td>
<td><code>logc_oh</code></td>
</tr>
</tbody>
</table>
</section>
<section id="principales-variables-secondaires-calculées" class="level3" data-number="22.4.2">
<h3 data-number="22.4.2" class="anchored" data-anchor-id="principales-variables-secondaires-calculées"><span class="header-section-number">22.4.2</span> Principales variables secondaires calculées</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th>Symbole</th>
<th>Signification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(n_\text{CH}\)</span></td>
<td>Teneur en moles de portlandite par litre de béton</td>
</tr>
<tr class="even">
<td><span class="math inline">\(n_\text{CSH2}\)</span></td>
<td>Teneur en moles de gypse (CaSO₄·2H₂O)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(n_\text{AFt}\)</span></td>
<td>Teneur en moles d’ettringite (<span class="math inline">\(\text{C}_6\text{AS}_3\text{H}_{32}\)</span>)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(n_\text{AFm}\)</span></td>
<td>Teneur en moles de monosulfoaluminate (<span class="math inline">\(\text{C}_4\text{ASH}_{12}\)</span>)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(n_\text{C3AH6}\)</span></td>
<td>Teneur en moles d’hydrogrenat (<span class="math inline">\(\text{C}_3\text{AH}_6\)</span>)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\phi\)</span></td>
<td>Porosité instantanée (modifiée par les réactions solides)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(P_c\)</span></td>
<td>Pression de cristallisation de l’AFt en confinement (Pa)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\varepsilon\)</span></td>
<td>Déformation de gonflement libre</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(D\)</span></td>
<td>Variable d’endommagement (<span class="math inline">\(0\)</span> = intact, <span class="math inline">\(1\)</span> = ruiné)</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="modèle-mathématique" class="level2" data-number="22.5">
<h2 data-number="22.5" class="anchored" data-anchor-id="modèle-mathématique"><span class="header-section-number">22.5</span> 4. Modèle mathématique</h2>
<section id="équations-de-conservation" class="level3" data-number="22.5.1">
<h3 data-number="22.5.1" class="anchored" data-anchor-id="équations-de-conservation"><span class="header-section-number">22.5.1</span> 4.1 Équations de conservation</h3>
<p>Le modèle résout six bilans de conservation couplés (Volumes Finis, <code>FVM.h</code>) :</p>
<ol type="1">
<li><p><strong>Conservation du soufre</strong> (S, sous forme <span class="math inline">\(\text{SO}_4^{2-}\)</span> et complexes) : <span class="math display">\[\frac{\partial N_S}{\partial t} + \nabla \cdot \mathbf{W}_S = 0\]</span></p></li>
<li><p><strong>Conservation de la charge électrique</strong> (électroneutralité globale) : <span class="math display">\[\frac{\partial N_q}{\partial t} + \nabla \cdot \mathbf{W}_q = 0\]</span></p></li>
<li><p><strong>Conservation du calcium</strong> (dissous + solide CH + CSH + CSH₂ + AFt + AFm + C₃AH₆) : <span class="math display">\[\frac{\partial N_\text{Ca}}{\partial t} + \nabla \cdot \mathbf{W}_\text{Ca} = 0\]</span></p></li>
<li><p><strong>Conservation du potassium</strong> : <span class="math display">\[\frac{\partial N_K}{\partial t} + \nabla \cdot \mathbf{W}_K = 0\]</span></p></li>
<li><p><strong>Conservation de l’aluminium</strong> (dissous + solide AH₃ + AFm + AFt + C₃AH₆) : <span class="math display">\[\frac{\partial N_\text{Al}}{\partial t} + \nabla \cdot \mathbf{W}_\text{Al} = 0\]</span></p></li>
<li><p><strong>Electroneutralité locale</strong> (fermeture du système) : <span class="math display">\[\sum_i z_i c_i = 0\]</span></p></li>
</ol>
<p>où <span class="math inline">\(N_x = \phi \, c_x^{\text{total}} + n_x^{\text{solide}}\)</span> est la teneur totale (liquide + solide) par unité de volume de béton.</p>
</section>
<section id="chimie-de-la-solution-interstitielle" class="level3" data-number="22.5.2">
<h3 data-number="22.5.2" class="anchored" data-anchor-id="chimie-de-la-solution-interstitielle"><span class="header-section-number">22.5.2</span> 4.2 Chimie de la solution interstitielle</h3>
<p>Le module <code>HardenedCementChemistry.h</code> résout l’équilibre chimique complet de la solution de pores du béton. Les espèces considérées sont :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Espèce</th>
<th>Symbole</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hydroxyle</td>
<td><span class="math inline">\(\text{OH}^-\)</span></td>
</tr>
<tr class="even">
<td>Proton</td>
<td><span class="math inline">\(\text{H}^+\)</span></td>
</tr>
<tr class="odd">
<td>Calcium libre</td>
<td><span class="math inline">\(\text{Ca}^{2+}\)</span></td>
</tr>
<tr class="even">
<td>Complexes calciques</td>
<td><span class="math inline">\(\text{CaOH}^+\)</span></td>
</tr>
<tr class="odd">
<td>Silicates dissous</td>
<td><span class="math inline">\(\text{H}_2\text{SiO}_4^{2-}\)</span>, <span class="math inline">\(\text{H}_3\text{SiO}_4^-\)</span>, <span class="math inline">\(\text{H}_4\text{SiO}_4\)</span></td>
</tr>
<tr class="even">
<td>Complexes Ca-Si</td>
<td><span class="math inline">\(\text{CaH}_2\text{SiO}_4\)</span>, <span class="math inline">\(\text{CaH}_3\text{SiO}_4^+\)</span></td>
</tr>
<tr class="odd">
<td>Sulfates</td>
<td><span class="math inline">\(\text{SO}_4^{2-}\)</span>, <span class="math inline">\(\text{HSO}_4^-\)</span>, <span class="math inline">\(\text{H}_2\text{SO}_4\)</span></td>
</tr>
<tr class="even">
<td>Complexes Ca-sulfate</td>
<td><span class="math inline">\(\text{CaSO}_4^\text{aq}\)</span>, <span class="math inline">\(\text{CaHSO}_4^+\)</span></td>
</tr>
<tr class="odd">
<td>Potassium</td>
<td><span class="math inline">\(\text{K}^+\)</span>, <span class="math inline">\(\text{KOH}^\text{aq}\)</span></td>
</tr>
<tr class="even">
<td>Aluminates</td>
<td><span class="math inline">\(\text{Al}(\text{OH})_4^-\)</span></td>
</tr>
</tbody>
</table>
<p>Ces concentrations sont toutes dérivées des 6 inconnues primaires via les constantes d’équilibre thermodynamique à <span class="math inline">\(T = 293\,\text{K}\)</span>.</p>
</section>
<section id="réactions-avec-les-phases-solides" class="level3" data-number="22.5.3">
<h3 data-number="22.5.3" class="anchored" data-anchor-id="réactions-avec-les-phases-solides"><span class="header-section-number">22.5.3</span> 4.3 Réactions avec les phases solides</h3>
<p>Les phases solides se dissolvent ou précipitent selon leur état de saturation :</p>
<section id="portlandite-textch-textcaoh_2" class="level4">
<h4 class="anchored" data-anchor-id="portlandite-textch-textcaoh_2">Portlandite — <span class="math inline">\(\text{CH} = \text{Ca(OH)}_2\)</span></h4>
<p>Dissolution contrôlée par le bilan de calcium solide : <span class="math display">\[n_\text{CH} = N_\text{CH}^{\text{ref}} \cdot \max(z_\text{Ca}, 0)\]</span></p>
<p>La variable <span class="math inline">\(z_\text{Ca}\)</span> décroît quand le calcium solide est consommé par les sulfates ou lixivié.</p>
</section>
<section id="gypse-textcsh_2-textcaso_4-cdot-2texth_2texto-cinétique" class="level4">
<h4 class="anchored" data-anchor-id="gypse-textcsh_2-textcaso_4-cdot-2texth_2texto-cinétique">Gypse — <span class="math inline">\(\text{CSH}_2 = \text{CaSO}_4 \cdot 2\text{H}_2\text{O}\)</span> (Cinétique)</h4>
<p><span class="math display">\[n_\text{CSH2}(t+\Delta t) = \max\!\left(n_\text{CSH2}(t) + \Delta t \cdot R_\text{CSH2} \cdot (S_\text{CSH2} - 1),\, 0\right)\]</span></p>
<p>où <span class="math inline">\(S_\text{CSH2}\)</span> est l’indice de saturation (rapport activité/produit de solubilité) et <span class="math inline">\(R_\text{CSH2}\)</span> le taux cinétique.</p>
</section>
<section id="ettringite-textaft-textc_6textas_3texth_32-cinétique-avec-confinement" class="level4">
<h4 class="anchored" data-anchor-id="ettringite-textaft-textc_6textas_3texth_32-cinétique-avec-confinement">Ettringite — <span class="math inline">\(\text{AFt} = \text{C}_6\text{AS}_3\text{H}_{32}\)</span> (Cinétique avec confinement)</h4>
<p>La cinétique de précipitation de l’AFt est plus élaborée : elle distingue la <strong>croissance en interface libre</strong> (paroi de pore) et la <strong>croissance en confinement</strong> (pore rempli), cette dernière générant une pression :</p>
<p><span class="math display">\[n_\text{AFt}(t+\Delta t) = \max\!\left(n_\text{AFt}(t) + \Delta t \cdot R_\text{AFt} \cdot f(\beta, \beta_p),\, 0\right)\]</span></p>
<p>où <span class="math inline">\(\beta = S_\text{AFt}\)</span> (indice de sursaturation global) et <span class="math inline">\(\beta_p\)</span> est l’indice d’équilibre au niveau de l’interface cristal-liquide confiné.</p>
</section>
<section id="monosulfoaluminate-textafm-textc_4textash_12-et-hydrogrenat-textc_3textah_6-cinétique" class="level4">
<h4 class="anchored" data-anchor-id="monosulfoaluminate-textafm-textc_4textash_12-et-hydrogrenat-textc_3textah_6-cinétique">Monosulfoaluminate — <span class="math inline">\(\text{AFm} = \text{C}_4\text{ASH}_{12}\)</span> et Hydrogrenat — <span class="math inline">\(\text{C}_3\text{AH}_6\)</span> (Cinétique)</h4>
<p><span class="math display">\[n_x(t+\Delta t) = \max\!\left(n_x(t) + \Delta t \cdot R_x \cdot (S_x - 1),\, 0\right)\]</span></p>
</section>
</section>
<section id="pression-de-cristallisation-et-endommagement" class="level3" data-number="22.5.4">
<h3 data-number="22.5.4" class="anchored" data-anchor-id="pression-de-cristallisation-et-endommagement"><span class="header-section-number">22.5.4</span> 4.4 Pression de cristallisation et endommagement</h3>
<p>Lorsque l’AFt précipite dans un pore de rayon <span class="math inline">\(r\)</span>, il génère une surpression donnée par la relation de <strong>Kelvin-Thomson</strong> :</p>
<p><span class="math display">\[P_c = \frac{RT}{V_\text{AFt}} \ln(\beta)\]</span></p>
<p>où <span class="math inline">\(\beta\)</span> est l’indice de sursaturation de l’AFt par rapport à l’équilibre confiné et <span class="math inline">\(V_\text{AFt} = 710.32\,\text{cm}^3/\text{mol}\)</span> est le volume molaire de l’ettringite.</p>
<p>L’équilibre thermodynamique à l’interface cristal-liquide dans un pore de rayon <span class="math inline">\(r\)</span> est : <span class="math display">\[\beta_\text{eq}(r) = \exp\!\left(\frac{2\,\Gamma_\text{AFt}\,V_\text{AFt}}{RT \cdot r}\right)\]</span></p>
<p>avec <span class="math inline">\(\Gamma_\text{AFt} = 0.1\,\text{N/m}\)</span> la tension superficielle.</p>
<p>La pression de cristallisation volumétriquement intégrée produit une <strong>déformation de gonflement libre</strong> <span class="math inline">\(\varepsilon\)</span>. Quand <span class="math inline">\(\varepsilon\)</span> dépasse le seuil <span class="math inline">\(\varepsilon_0\)</span>, le béton s’endommage selon une loi exponentielle :</p>
<p><span class="math display">\[D(\varepsilon) = 1 - \frac{\varepsilon_0}{\varepsilon} \exp\!\left(-\frac{\varepsilon - \varepsilon_0}{\varepsilon_f}\right)\]</span></p>
<p>où <span class="math inline">\(\varepsilon_0\)</span> est la déformation seuil et <span class="math inline">\(\varepsilon_f\)</span> la déformation caractéristique de rupture. L’endommagement <span class="math inline">\(D\)</span> réduit la contrainte effective et augmente la perméabilité aux ions.</p>
</section>
<section id="loi-de-transport-diffusion-ionique" class="level3" data-number="22.5.5">
<h3 data-number="22.5.5" class="anchored" data-anchor-id="loi-de-transport-diffusion-ionique"><span class="header-section-number">22.5.5</span> 4.5 Loi de transport (diffusion ionique)</h3>
<p>Le flux de chaque ion <span class="math inline">\(i\)</span> (de charge <span class="math inline">\(z_i\)</span> et coefficient de diffusion <span class="math inline">\(D_i\)</span>) dans la solution de pores est donné par l’équation de <strong>Nernst-Planck</strong> :</p>
<p><span class="math display">\[\mathbf{W}_i = -\phi \, \tau(\phi) \left( D_i \nabla c_i + z_i \frac{F D_i}{RT} c_i \nabla \psi \right)\]</span></p>
<p>où <span class="math inline">\(\tau(\phi)\)</span> est la tortuosité effective selon la loi de Bazant-Najjar :</p>
<p><span class="math display">\[\tau(\phi) = 0.001 + 0.07\phi^2 + H(\phi - 0.18) \cdot 1.8(\phi - 0.18)^2\]</span></p>
<p>Le module <code>CementSolutionDiffusion.h</code> gère les coefficients <span class="math inline">\(D_i\)</span> pour chaque ion.</p>
<hr>
</section>
</section>
<section id="conditions-aux-limites-et-initiales" class="level2" data-number="22.6">
<h2 data-number="22.6" class="anchored" data-anchor-id="conditions-aux-limites-et-initiales"><span class="header-section-number">22.6</span> 5. Conditions aux limites et initiales</h2>
<section id="conditions-initiales" class="level3" data-number="22.6.1">
<h3 data-number="22.6.1" class="anchored" data-anchor-id="conditions-initiales"><span class="header-section-number">22.6.1</span> Conditions initiales</h3>
<p>Le béton est initialement dans un état d’équilibre chimique “intact” défini par les teneurs initiales en phases solides (<span class="math inline">\(N_\text{CH}\)</span>, <span class="math inline">\(N_\text{CSH}\)</span>, <span class="math inline">\(N_\text{C3AH6}\)</span>…) et une concentration en sulfates très faible (<span class="math inline">\(\log c_{\text{SO}_4} = -6\)</span>, soit <span class="math inline">\(c_{\text{SO}_4} = 10^{-6}\,\text{mol/L}\)</span>).</p>
</section>
<section id="conditions-aux-limites" class="level3" data-number="22.6.2">
<h3 data-number="22.6.2" class="anchored" data-anchor-id="conditions-aux-limites"><span class="header-section-number">22.6.2</span> Conditions aux limites</h3>
<p>Le système est <strong>exposé d’un côté</strong> (région 1, <span class="math inline">\(x=0\)</span>) à une solution sulfatée dont la concentration en <span class="math inline">\(\text{SO}_4^{2-}\)</span> augmente au cours du temps selon les fonctions définies dans le fichier d’entrée. L’autre face (région 3, <span class="math inline">\(x=L\)</span>) est laissée sans flux (Neumann nul implicite).</p>
<hr>
</section>
</section>
<section id="cas-test-attaque-sulfatique-dun-échantillon-de-béton-basesulfaco" class="level2" data-number="22.7">
<h2 data-number="22.7" class="anchored" data-anchor-id="cas-test-attaque-sulfatique-dun-échantillon-de-béton-basesulfaco"><span class="header-section-number">22.7</span> 6. Cas test : Attaque sulfatique d’un échantillon de béton (<code>base/Sulfaco/</code>)</h2>
<section id="géométrie" class="level3" data-number="22.7.1">
<h3 data-number="22.7.1" class="anchored" data-anchor-id="géométrie"><span class="header-section-number">22.7.1</span> Géométrie</h3>
<p>L’échantillon est un <strong>domaine 1D de longueur <span class="math inline">\(L = 1\,\text{dm}\)</span></strong>, discrétisé en un seul élément fini de volumes finis avec deux nœuds (représentation d’un “point matériel” homogène sans gradient spatial interne).</p>
</section>
<section id="scénario-simulé" class="level3" data-number="22.7.2">
<h3 data-number="22.7.2" class="anchored" data-anchor-id="scénario-simulé"><span class="header-section-number">22.7.2</span> Scénario simulé</h3>
<p>Il s’agit d’une simulation d’un <strong>point de matériau unique</strong> (pas de gradient spatial) exposé à un apport croissant de sulfates. Les concentrations imposées en <span class="math inline">\(x=0\)</span> varient selon des fonctions temporelles définies dans le fichier d’entrée :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable imposée</th>
<th><span class="math inline">\(t=0\)</span></th>
<th><span class="math inline">\(t=8640\,\text{s}\)</span></th>
<th><span class="math inline">\(t=864000\,\text{s}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\log c_{\text{SO}_4}\)</span></td>
<td><span class="math inline">\(-6\)</span></td>
<td><span class="math inline">\(-2.556\)</span></td>
<td><span class="math inline">\(-0.456\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\log c_K\)</span></td>
<td><span class="math inline">\(-5.7\)</span></td>
<td><span class="math inline">\(-2.256\)</span></td>
<td><span class="math inline">\(-0.156\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\log c_\text{OH}\)</span></td>
<td><span class="math inline">\(-2\)</span> (pH 12)</td>
<td><span class="math inline">\(-2\)</span></td>
<td><span class="math inline">\(-2\)</span></td>
</tr>
</tbody>
</table>
<p>La durée totale simulée est de <span class="math inline">\(3.5 \times 10^6\,\text{s} \approx 40\,\text{jours}\)</span>.</p>
</section>
<section id="résultats-attendus-sorties-.gp" class="level3" data-number="22.7.3">
<h3 data-number="22.7.3" class="anchored" data-anchor-id="résultats-attendus-sorties-.gp"><span class="header-section-number">22.7.3</span> Résultats attendus (sorties <code>.gp</code>)</h3>
<p>Le fichier Gnuplot <code>Sulfaco.gp</code> trace neuf figures de post-traitement :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Figure</th>
<th>Fichier</th>
<th>Contenu physique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>Strain.eps</code></td>
<td>Déformation de gonflement <span class="math inline">\(\varepsilon(t)\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><code>EttringiteSaturationIndex.eps</code></td>
<td>Indice de saturation <span class="math inline">\(S_\text{AFt}(t)\)</span> (log-log)</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>EttringiteContent.eps</code></td>
<td>Teneur en ettringite <span class="math inline">\(n_\text{AFt}(t)\)</span> (mol/L de béton)</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>CrystallizationPressure.eps</code></td>
<td>Pression de cristallisation <span class="math inline">\(P_c(t)\)</span> (Pa)</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>pH.eps</code></td>
<td>Évolution du pH de la solution interstitielle</td>
</tr>
<tr class="even">
<td>6</td>
<td><code>SaturationIndexes.eps</code></td>
<td>Indices de saturation : AFt et gypse (CSH₂)</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>SolidContents.eps</code></td>
<td>Évolution des phases solides : CH, AFt, C₃AH₆</td>
</tr>
<tr class="even">
<td>8</td>
<td><code>IonConcentrations.eps</code></td>
<td>Concentration en <span class="math inline">\(\text{SO}_4^{2-}\)</span> (mol/L)</td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>StressStrain.eps</code></td>
<td>Contrainte effective <span class="math inline">\(S_c \cdot P_c\)</span> vs.&nbsp;déformation</td>
</tr>
</tbody>
</table>
<p>La séquence physique attendue est : 1. Les sulfates entrant réagissent d’abord avec <strong>C₃AH₆</strong> (hydrogrenat) et <strong>AFm</strong> (monosulfoaluminate), qui se convertissent en <strong>AFt</strong> (ettringite). 2. L’indice de saturation de l’AFt croît, la <strong>pression de cristallisation</strong> augmente. 3. Quand <span class="math inline">\(P_c\)</span> dépasse la résistance à la traction (déformation <span class="math inline">\(\varepsilon &gt; \varepsilon_0\)</span>), <strong>l’endommagement</strong> <span class="math inline">\(D\)</span> s’enclenche et la déformation libre <span class="math inline">\(\varepsilon\)</span> augmente brutalement. 4. La <strong>portlandite</strong> (CH) se dissout progressivement, tamponnant le pH.</p>
<hr>
</section>
</section>
<section id="paramétrage-matériel-du-modèle" class="level2" data-number="22.8">
<h2 data-number="22.8" class="anchored" data-anchor-id="paramétrage-matériel-du-modèle"><span class="header-section-number">22.8</span> 7. Paramétrage matériel du modèle</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 45%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Paramètre</th>
<th>Valeur dans <code>Sulfaco</code></th>
<th>Rôle physique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>porosity</code></td>
<td><span class="math inline">\(0.23\)</span></td>
<td>Porosité initiale du béton sain</td>
</tr>
<tr class="even">
<td><code>N_CH</code></td>
<td><span class="math inline">\(1.53\,\text{mol/L}\)</span></td>
<td>Teneur initiale en portlandite</td>
</tr>
<tr class="odd">
<td><code>N_CSH</code></td>
<td><span class="math inline">\(1.393\,\text{mol/L}\)</span></td>
<td>Teneur initiale en C-S-H (source Si)</td>
</tr>
<tr class="even">
<td><code>N_AH3</code></td>
<td><span class="math inline">\(10^{-6}\,\text{mol/L}\)</span></td>
<td>Gibbsite (quasi-nul, trace)</td>
</tr>
<tr class="odd">
<td><code>N_C3AH6</code></td>
<td><span class="math inline">\(0.2\,\text{mol/L}\)</span></td>
<td>Hydrogrenat initial (précurseur aluminium)</td>
</tr>
<tr class="even">
<td><code>N_CSH2</code>, <code>N_AFm</code>, <code>N_AFt</code></td>
<td><span class="math inline">\(0\)</span></td>
<td>Pas de gypse ni ettringite initiale</td>
</tr>
<tr class="odd">
<td><code>R_CSH2</code></td>
<td><span class="math inline">\(10^{-12}\,\text{mol/L/s}\)</span></td>
<td>Taux de précipitation du gypse (très lent)</td>
</tr>
<tr class="even">
<td><code>R_AFm</code></td>
<td><span class="math inline">\(10^{-6}\,\text{mol/L/s}\)</span></td>
<td>Taux de précipitation du monosulfoaluminate</td>
</tr>
<tr class="odd">
<td><code>R_C3AH6</code></td>
<td><span class="math inline">\(10^{-6}\,\text{mol/L/s}\)</span></td>
<td>Taux de dissolution de l’hydrogrenat</td>
</tr>
<tr class="even">
<td><code>A_i</code></td>
<td><span class="math inline">\(8.4 \times 10^{-8}\)</span></td>
<td>Taux de croissance de l’AFt en interface libre (<span class="math inline">\(a_r\)</span>)</td>
</tr>
<tr class="odd">
<td><code>A_p</code></td>
<td><span class="math inline">\(4.4 \times 10^{-9}\)</span></td>
<td>Taux de croissance de l’AFt en pore confiné (<span class="math inline">\(a_p\)</span>)</td>
</tr>
<tr class="even">
<td><code>K_bulk</code></td>
<td><span class="math inline">\(30.1\,\text{GPa}\)</span></td>
<td>Module de compression du béton sain</td>
</tr>
<tr class="odd">
<td><code>Biot</code></td>
<td><span class="math inline">\(0.54\)</span></td>
<td>Coefficient de Biot (couplage pression-déformation)</td>
</tr>
<tr class="even">
<td><code>Strain0</code></td>
<td><span class="math inline">\(4 \times 10^{-4}\)</span></td>
<td>Déformation seuil d’endommagement <span class="math inline">\(\varepsilon_0\)</span></td>
</tr>
<tr class="odd">
<td><code>Strainf</code></td>
<td><span class="math inline">\(6.4 \times 10^{-3}\)</span></td>
<td>Déformation caractéristique de rupture <span class="math inline">\(\varepsilon_f\)</span></td>
</tr>
<tr class="even">
<td><code>AlphaCoef</code></td>
<td><span class="math inline">\(0\)</span></td>
<td>Coefficient d’adsorption des sulfates sur les C-S-H (désactivé)</td>
</tr>
<tr class="odd">
<td><code>BetaCoef</code></td>
<td><span class="math inline">\(0.87\)</span></td>
<td>Coefficient de saturation dans l’isotherme d’adsorption</td>
</tr>
<tr class="even">
<td><code>Curves_log = Sat</code></td>
<td>Van Genuchten (<span class="math inline">\(m=0.2516\)</span>, <span class="math inline">\(r_0=155.82\,\text{nm}\)</span>)</td>
<td>Courbe de saturation liquide <span class="math inline">\(S_r(r)\)</span> dans les pores</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="description-pas-à-pas-des-fichiers-dentrée" class="level2" data-number="22.9">
<h2 data-number="22.9" class="anchored" data-anchor-id="description-pas-à-pas-des-fichiers-dentrée"><span class="header-section-number">22.9</span> 8. Description pas-à-pas des fichiers d’entrée</h2>
<section id="système-dunités-units" class="level3" data-number="22.9.1">
<h3 data-number="22.9.1" class="anchored" data-anchor-id="système-dunités-units"><span class="header-section-number">22.9.1</span> 8.1 Système d’unités (<code>Units</code>)</h3>
<pre><code>Units
Length = decimeter     # 1 unité de longueur = 1 dm
Time   = second        # 1 unité de temps = 1 s
Mass   = hectogram     # 1 unité de masse = 100 g</code></pre>
<p>Le choix du décimètre comme unité de longueur est cohérent avec les tailles d’éprouvettes de béton (quelques centimètres à décimètres). Les concentrations sont donc en <strong>mol/dm³ = mol/L</strong> et les diffusivités en <strong>dm²/s</strong>.</p>
</section>
<section id="géométrie-et-maillage-geometry-mesh" class="level3" data-number="22.9.2">
<h3 data-number="22.9.2" class="anchored" data-anchor-id="géométrie-et-maillage-geometry-mesh"><span class="header-section-number">22.9.2</span> 8.2 Géométrie et maillage (<code>Geometry</code>, <code>Mesh</code>)</h3>
<pre><code>Geometry
Dimension = 1  plan     # Problème 1D en coordonnées planes (cartésiennes)

Mesh
2                        # 2 nœuds
0. 1                     # Nœud 1 : x=0 (surface exposée)
1.                       # Nœud 2 : x=1 dm (cœur)
1                        # 1 élément
1                        # Élément linéaire reliant nœuds 1-2 (région 1)</code></pre>
<p>Le fichier maillage <code>Sulfaco.msh</code> (format Gmsh) définit explicitement 4 nœuds dont 2 nœuds de bord (type 15 = points) et 1 segment (type 1) entre <span class="math inline">\(x=0\)</span> et <span class="math inline">\(x=1\,\text{dm}\)</span>.</p>
</section>
<section id="matériau-material" class="level3" data-number="22.9.3">
<h3 data-number="22.9.3" class="anchored" data-anchor-id="matériau-material"><span class="header-section-number">22.9.3</span> 8.3 Matériau (<code>Material</code>)</h3>
<pre><code>Model = Sulfaco
porosity = 0.23
N_CH     = 1.53
N_CSH    = 1.393
N_AH3    = 1.e-6
N_C3AH6  = 0.2</code></pre>
<p>Ces lignes définissent la <strong>microstructure initiale</strong> du béton : portlandite et C-S-H sont les réservoirs de calcium qui contrôlent le tampon pH et la source de calcium pour les réactions sulfatiques.</p>
<pre><code>R_CSH2   = 1.e-12
R_AFm    = 1.e-6
R_C3AH6  = 1.e-6</code></pre>
<p>Ces constantes cinétiques (<code>R_x</code>, en mol/L/s) contrôlent la vitesse des transformations solides. <code>R_CSH2</code> très petit signifie que le gypse précipite très lentement ; <code>R_C3AH6</code> modéré permet une dissolution rapide de l’hydrogrenat en ettringite.</p>
<pre><code>A_i = 8.4e-8
A_p = 4.4e-9</code></pre>
<p>Coefficients de cinétique de croissance cristalline de l’AFt : <code>A_i</code> (interface libre, rapide) et <code>A_p</code> (pore confiné, 20 fois plus lent).</p>
<pre><code>K_bulk = 30.1e9
Biot = 0.54
Strain0 = 4.e-4
Strainf = 6.4e-3</code></pre>
<p>Paramètres mécaniques : le module de compression <span class="math inline">\(K_\text{bulk}\)</span> et le coefficient de Biot permettent de calculer la contrainte effective. <code>Strain0</code> et <code>Strainf</code> définissent la courbe d’endommagement : le béton commence à se fissurer à partir d’une déformation de <span class="math inline">\(4 \times 10^{-4}\)</span> et est totalement ruiné à <span class="math inline">\(\sim 7 \times 10^{-3}\)</span>.</p>
<pre><code>Curves_log = Sat  r = Range{r1 = 1.e-8 , r2 = 1.e-3 , n = 1000}
             S_r = Expressions(1){r0=155.82e-8; m = 0.2516 ; S_r = (1 + (r0/r)**(1/(1-m)))**(-m)}</code></pre>
<p>Courbe de saturation de van Genuchten : pour un rayon de pore <span class="math inline">\(r\)</span> (en m), <span class="math inline">\(S_r(r)\)</span> donne la fraction de pores plus petits que <span class="math inline">\(r\)</span> saturés en solution. Elle est tabulée sur 1000 points entre <span class="math inline">\(r=10\,\text{nm}\)</span> et <span class="math inline">\(r=1\,\text{mm}\)</span>.</p>
</section>
<section id="champs-fields" class="level3" data-number="22.9.4">
<h3 data-number="22.9.4" class="anchored" data-anchor-id="champs-fields"><span class="header-section-number">22.9.4</span> 8.4 Champs (<code>Fields</code>)</h3>
<pre><code>Fields
1
Value = 1   Gradient = 0 0 0   Point = 0 0 0</code></pre>
<p>Un seul champ scalaire uniforme (valeur 1, gradient nul) est défini. Il sert comme <strong>multiplicateur</strong> dans les fonctions d’initialisation et de conditions aux limites.</p>
</section>
<section id="initialisation-initialization" class="level3" data-number="22.9.5">
<h3 data-number="22.9.5" class="anchored" data-anchor-id="initialisation-initialization"><span class="header-section-number">22.9.5</span> 8.5 Initialisation (<code>Initialization</code>)</h3>
<pre><code>Initialization
6
Region = 1 Unknown = logc_so4   Field = 1 Function = 1
Region = 1 Unknown = psi        Field = 0 Function = 0
Region = 1 Unknown = z_ca       Field = 1 Function = 4
Region = 1 Unknown = z_al       Field = 1 Function = 3
Region = 1 Unknown = logc_k     Field = 1 Function = 2
Region = 1 Unknown = logc_oh    Field = 1 Function = 5</code></pre>
<p>Chaque ligne initialise une inconnue dans la région 1 (tout le domaine) à la valeur <code>Field × Function(t=0)</code> :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 39%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Inconnue</th>
<th>Valeur initiale</th>
<th>Signification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>logc_so4</code></td>
<td><span class="math inline">\(1 \times (-6) = -6\)</span></td>
<td><span class="math inline">\(c_{\text{SO}_4} = 10^{-6}\,\text{mol/L}\)</span> (béton sain, peu de sulfates)</td>
</tr>
<tr class="even">
<td><code>psi</code></td>
<td><span class="math inline">\(0 \times 0 = 0\)</span></td>
<td>Potentiel électrique nul à l’état initial</td>
</tr>
<tr class="odd">
<td><code>z_ca</code></td>
<td><span class="math inline">\(1 \times 1 = 1\)</span></td>
<td>Portlandite intacte : <span class="math inline">\(n_\text{CH} = N_\text{CH} \times 1\)</span></td>
</tr>
<tr class="even">
<td><code>z_al</code></td>
<td><span class="math inline">\(1 \times 1 = 1\)</span></td>
<td>AH₃ solide intact : <span class="math inline">\(n_\text{AH3} = N_\text{AH3} \times 1\)</span></td>
</tr>
<tr class="odd">
<td><code>logc_k</code></td>
<td><span class="math inline">\(1 \times (-5.7) = -5.7\)</span></td>
<td><span class="math inline">\(c_K \approx 2 \times 10^{-6}\,\text{mol/L}\)</span></td>
</tr>
<tr class="even">
<td><code>logc_oh</code></td>
<td><span class="math inline">\(1 \times (-2) = -2\)</span></td>
<td>pH <span class="math inline">\(= 12\)</span> (<span class="math inline">\(c_{\text{OH}^-} = 10^{-2}\,\text{mol/L}\)</span>)</td>
</tr>
</tbody>
</table>
</section>
<section id="fonctions-temporelles-functions" class="level3" data-number="22.9.6">
<h3 data-number="22.9.6" class="anchored" data-anchor-id="fonctions-temporelles-functions"><span class="header-section-number">22.9.6</span> 8.6 Fonctions temporelles (<code>Functions</code>)</h3>
<pre><code>Functions
5
N = 5 F(0) = -6     F(8640) = -2.556  F(86400) = -1.556  F(345600) = -0.954  F(864000) = -0.456
N = 5 F(0) = -5.7   F(8640) = -2.256  F(86400) = -1.256  F(345600) = -0.654  F(864000) = -0.156
N = 2 F(0) = -7.32  F(86400) = -6.32
N = 2 F(0) = 1      F(86400) = 1
N = 2 F(0) = -2     F(86400) = -2</code></pre>
<p>Cinq fonctions d’interpolation temporelle linéaire par morceaux (avec <code>N</code> points) :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Fonction</th>
<th>Utilisation</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>logc_so4</code> en CL</td>
<td><span class="math inline">\(\log c_{\text{SO}_4}\)</span> : monte de <span class="math inline">\(-6\)</span> à <span class="math inline">\(-0.456\)</span> (de <span class="math inline">\(10^{-6}\)</span> à <span class="math inline">\(0.35\,\text{mol/L}\)</span>) en <span class="math inline">\(10\,\text{jours}\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><code>logc_k</code> en CL</td>
<td><span class="math inline">\(\log c_K\)</span> : monte de <span class="math inline">\(-5.7\)</span> à <span class="math inline">\(-0.156\)</span> (de <span class="math inline">\(2\times10^{-6}\)</span> à <span class="math inline">\(0.7\,\text{mol/L}\)</span>) en <span class="math inline">\(10\,\text{jours}\)</span></td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>z_al</code> initial</td>
<td>Constante <span class="math inline">\(= 1\)</span> (aluminium solide stable)</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>z_ca</code> initial</td>
<td>Pente légère (dissolution lente de CH au cours du 1er jour)</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>logc_oh</code> en CL</td>
<td>pH constant à 12 (<span class="math inline">\(c_{\text{OH}^-} = 10^{-2}\,\text{mol/L}\)</span>)</td>
</tr>
</tbody>
</table>
</section>
<section id="conditions-aux-limites-boundary-conditions" class="level3" data-number="22.9.7">
<h3 data-number="22.9.7" class="anchored" data-anchor-id="conditions-aux-limites-boundary-conditions"><span class="header-section-number">22.9.7</span> 8.7 Conditions aux limites (<code>Boundary Conditions</code>)</h3>
<pre><code>Boundary Conditions
4
Region = 1 Unknown = logc_so4   Field = 1 Function = 1
Region = 1 Unknown = psi        Field = 0 Function = 0
Region = 1 Unknown = logc_k     Field = 1 Function = 2
Region = 1 Unknown = logc_oh    Field = 1 Function = 5</code></pre>
<p>Les conditions aux limites sont appliquées à la <strong>région 1</strong> (surface exposée <span class="math inline">\(x=0\)</span>) : - Les concentrations en sulfate et potassium sont <strong>imposées</strong> et augmentent au cours du temps (fonctions 1 et 2). - Le potentiel électrique est maintenu à <strong>zéro</strong> (référence). - Le pH est <strong>maintenu à 12</strong> tout au long de la simulation (fonction 5, constante). - <span class="math inline">\(z_\text{Ca}\)</span> et <span class="math inline">\(z_\text{Al}\)</span> ne sont <strong>pas prescrits</strong> en CL (lignes commentées) : le calcium solide évolue librement par dissolution/précipitation.</p>
</section>
<section id="points-dobservation-points" class="level3" data-number="22.9.8">
<h3 data-number="22.9.8" class="anchored" data-anchor-id="points-dobservation-points"><span class="header-section-number">22.9.8</span> 8.8 Points d’observation (<code>Points</code>)</h3>
<pre><code>Points
1
0.5</code></pre>
<p>Un seul point d’observation est défini, à <span class="math inline">\(x = 0.5\,\text{dm}\)</span> (centre de l’échantillon). C’est à ce point que les variables secondaires (colonnes du fichier <code>.p1</code>) sont enregistrées au cours du temps.</p>
</section>
<section id="fenêtre-temporelle-et-critères-de-convergence" class="level3" data-number="22.9.9">
<h3 data-number="22.9.9" class="anchored" data-anchor-id="fenêtre-temporelle-et-critères-de-convergence"><span class="header-section-number">22.9.9</span> 8.9 Fenêtre temporelle et critères de convergence</h3>
<pre><code>Dates
2
0.  3.5e6       # t=0 s à t=3.5×10⁶ s ≈ 40 jours

Objective Variations
logc_so4  = 1.e-3   # Variation relative tolérée pour l'inconnue sulfate
z_ca      = 1.e-3
psi       = 1.e-1
logc_k    = 1.e-1
z_al      = 1.e-1
logc_oh   = 1.e-1

Iterative Process
Iter = 20       # Nombre max d'itérations Newton-Raphson par pas de temps
Tol  = 1.e-4    # Tolérance sur le résidu global

Time Steps
Dtini = 1.e3    # Pas de temps initial : 1000 s ≈ 17 min
Dtmax = 1.e3    # Pas de temps maximum : 1000 s (fixe)</code></pre>
<p>Le pas de temps fixe de <span class="math inline">\(1000\,\text{s}\)</span> est adapté aux cinétiques chimiques les plus rapides (AFm, C₃AH₆ avec <span class="math inline">\(R_x = 10^{-6}\,\text{mol/L/s}\)</span>). La tolérance <code>Objective Variations</code> contrôle le pas de temps adaptatif de BIL : si la variation d’une inconnue dépasse son seuil, le pas est découpé.</p>
<hr>
</section>
</section>
<section id="références-bibliographiques" class="level2" data-number="22.10">
<h2 data-number="22.10" class="anchored" data-anchor-id="références-bibliographiques"><span class="header-section-number">22.10</span> 9. Références bibliographiques</h2>
<ul>
<li><p><strong>Biot, M. A.</strong> (1941). General theory of three-dimensional consolidation. <em>Journal of applied physics</em>, 12(2), 155–164. — Fonde le couplage pression interstitielle / déformation (coefficient de Biot <span class="math inline">\(b = 0.54\)</span> utilisé dans le modèle).</p></li>
<li><p><strong>Coussy, O.</strong> (2004). <em>Poromechanics</em>. John Wiley &amp; Sons. — Traitement rigoureux de la pression de cristallisation en milieu poreux (Eq. de Kelvin-Thomson appliquée aux cristaux en croissance dans les pores).</p></li>
<li><p><strong>Flatt, R. J. &amp; Scherer, G. W.</strong> (2008). Thermodynamics of crystallization stresses in DEF. <em>Cement and Concrete Research</em>, 38(3), 325–336. — Base thermodynamique du calcul de pression de cristallisation de l’ettringite différée <span class="math inline">\(P_c = \frac{RT}{V_\text{AFt}}\ln\beta\)</span>.</p></li>
<li><p><strong>Montoya, A. G., et al.</strong> (2016). A chemo-mechanical model for sulfate attack in concrete — Fournit le cadre du couplage chimie-mécanique utilisé dans Sulfaco (endommagement, gonflement, altération de porosité).</p></li>
<li><p><strong>Nernst, W. &amp; Planck, M.</strong> (1890). Théorie de diffusion ionique couplée au potentiel électrique. — Équation de Nernst-Planck pour le transport d’ions en solution poreuse (<span class="math inline">\(\mathbf{W}_i = -\phi\tau(D_i \nabla c_i + z_i \frac{FD_i}{RT} c_i \nabla\psi)\)</span>).</p></li>
<li><p><strong>Bazant, Z. P. &amp; Najjar, L. J.</strong> (1972). Nonlinear water diffusion in nonsaturated concrete. <em>Matériaux et Construction</em>, 5(25), 3–20. — Loi de tortuosité <span class="math inline">\(\tau(\phi)\)</span> utilisée dans le calcul des flux diffusifs.</p></li>
<li><p><strong>Van Genuchten, M. Th.</strong> (1980). A closed-form equation for predicting the hydraulic conductivity of unsaturated soils. <em>Soil Science Society of America Journal</em>, 44(5), 892–898. — Modèle de courbe de saturation <span class="math inline">\(S_r(r)\)</span> utilisé pour la distribution de rayons de pores (paramètres <span class="math inline">\(m=0.2516\)</span>, <span class="math inline">\(r_0 = 155.82\,\text{nm}\)</span>).</p></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chloricem_model.html" class="pagination-link" aria-label="Modèle Chloricem — Durabilité des matériaux cimentaires : pénétration des chlorures (1D)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Modèle Chloricem — Durabilité des matériaux cimentaires : pénétration des chlorures (1D)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Sulfuricem_model.html" class="pagination-link" aria-label="Modèle Sulfuricem — Attaque à l'acide sulfurique des matériaux cimentaires">
        <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Modèle Sulfuricem — Attaque à l’acide sulfurique des matériaux cimentaires</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Modèle Sulfaco — Attaque Sulfatique Interne/Externe du Béton</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Fichiers sources :**</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; </span><span class="in">`src/Models/ModelFiles/Sulfaco.c`</span><span class="at"> · </span><span class="in">`base/Sulfaco/Sulfaco`</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Auteurs du modèle :** Gu, Dangla (Université Gustave Eiffel)</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Titre interne :** *"Internal/External sulfate attack of concrete (2017)"*</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## Table des matières</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span><span class="co">[</span><span class="ot">Contexte et objectif</span><span class="co">](#1-contexte-et-objectif)</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span><span class="co">[</span><span class="ot">Hypothèses</span><span class="co">](#2-hypothèses)</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span><span class="co">[</span><span class="ot">Variables et notation</span><span class="co">](#3-variables-et-notation)</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span><span class="co">[</span><span class="ot">Modèle mathématique</span><span class="co">](#4-modèle-mathématique)</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>4.1 <span class="co">[</span><span class="ot">Équations de conservation</span><span class="co">](#41-équations-de-conservation)</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>4.2 <span class="co">[</span><span class="ot">Chimie de la solution interstitielle</span><span class="co">](#42-chimie-de-la-solution-interstitielle)</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>4.3 <span class="co">[</span><span class="ot">Réactions avec les phases solides</span><span class="co">](#43-réactions-avec-les-phases-solides)</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>4.4 <span class="co">[</span><span class="ot">Pression de cristallisation et endommagement</span><span class="co">](#44-pression-de-cristallisation-et-endommagement)</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>4.5 <span class="co">[</span><span class="ot">Loi de transport (diffusion ionique)</span><span class="co">](#45-loi-de-transport-diffusion-ionique)</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span><span class="co">[</span><span class="ot">Conditions aux limites et initiales</span><span class="co">](#5-conditions-aux-limites-et-initiales)</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span><span class="co">[</span><span class="ot">Cas test : Attaque sulfatique d'un échantillon de béton (`base/Sulfaco/`)</span><span class="co">](#6-cas-test--attaque-sulfatique-dun-échantillon-de-béton-basesulfaco)</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span><span class="co">[</span><span class="ot">Paramétrage matériel du modèle</span><span class="co">](#7-paramétrage-matériel-du-modèle)</span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span><span class="co">[</span><span class="ot">Description pas-à-pas des fichiers d'entrée</span><span class="co">](#8-description-pas-à-pas-des-fichiers-dentrée)</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span><span class="co">[</span><span class="ot">Références bibliographiques</span><span class="co">](#9-références-bibliographiques)</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Contexte et objectif</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>Le modèle **Sulfaco** simule la **dégradation chimique du béton armé par attaque sulfatique** (interne ou externe). Ce phénomène de durabilité est l'une des principales causes de détérioration à long terme des infrastructures en béton (ouvrages d'art, fondations, tunnels en terrain gypseux).</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>L'attaque sulfatique se produit lorsque des ions sulfate ($\text{SO}_4^{2-}$) pénètrent dans la pâte de ciment durcie (attaque externe) ou sont libérés par des agrégats sulfatés (attaque interne). Ces ions réagissent avec les phases solides alumineuses du ciment hydraté pour former de l'**ettringite secondaire** ($\text{AFt} = \text{C}_6\text{AS}_3\text{H}_{32}$). La formation d'ettringite en milieu confiné génère une **pression de cristallisation** qui excède la résistance à la traction du béton, provoquant fissuration et délaminage.</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a><span class="in">```mermaid</span></span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>graph TD</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>    A[<span class="ot">"</span><span class="st">Ions SO₄²⁻ en solution&lt;br&gt;(apport externe ou interne)</span><span class="ot">"</span>] --&gt; B(<span class="ot">"</span><span class="st">Chimie de la solution de pores&lt;br&gt;Équilibre acido-basique, complexes ioniques</span><span class="ot">"</span>)</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>    B --&gt;|Sursaturation| C[<span class="ot">"</span><span class="st">Formation de Gypse (CSH₂)&lt;br&gt;et d'Ettringite (AFt)</span><span class="ot">"</span>]</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>    B --&gt;|Dissolution| D[<span class="ot">"</span><span class="st">Dissolution de Portlandite (CH)&lt;br&gt;et C3AH6</span><span class="ot">"</span>]</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a>    C --&gt; E(<span class="ot">"</span><span class="st">Variation de porosité ΔΦ&lt;br&gt;Fermeture des pores</span><span class="ot">"</span>)</span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a>    E --&gt; F[<span class="ot">"</span><span class="st">Pression de cristallisation P_c&lt;br&gt;(si AFt en milieu confiné)</span><span class="ot">"</span>]</span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a>    F --&gt; G[<span class="ot">"</span><span class="st">Endommagement mécanique D(ε)</span><span class="ot">"</span>]</span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a>    G --&gt;|Ouverture de microfissures| E</span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a>    E --&gt; H[<span class="ot">"</span><span class="st">Transport ionique&lt;br&gt;(diffusion + migration électrique)</span><span class="ot">"</span>]</span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a>    H --&gt; B</span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-51"><a href="#cb15-51" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Hypothèses</span></span>
<span id="cb15-52"><a href="#cb15-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-53"><a href="#cb15-53" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Isotherme** : La température est fixée à $T = 293\,\text{K}$ ($20°\text{C}$). Les constantes d'équilibre thermodynamique sont évaluées à cette température.</span>
<span id="cb15-54"><a href="#cb15-54" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Milieu poreux saturé** : La solution de pores occupe l'ensemble de la porosité (pas de phase gazeuse). La saturation $S_r$ est décrite par une courbe tabulée en fonction du rayon de pore $r$.</span>
<span id="cb15-55"><a href="#cb15-55" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Cinétique de dissolution/précipitation** : Les réactions des phases solides (CSH₂, AFt, AFm, C₃AH₆) sont pilotées par des lois cinétiques du premier ordre en écart à la sursaturation, avec des taux $R_x$ (mol/L/s). La portlandite (CH) et l'ettringite (AFt à l'équilibre) obéissent à un bilan de matière direct.</span>
<span id="cb15-56"><a href="#cb15-56" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Électroneutralité** : La charge électrique totale de la solution est nulle. Cette contrainte ferme le système : elle définit la concentration en $\text{OH}^-$ à partir des autres ions.</span>
<span id="cb15-57"><a href="#cb15-57" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Pression de cristallisation** : La pression exercée par un cristal d'AFt en croissance dans un pore de rayon $r$ est donnée par la thermodynamique de Laplace (équation de Kelvin-Thomson).</span>
<span id="cb15-58"><a href="#cb15-58" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Endommagement uniaxial** : Une déformation de gonflement $\varepsilon$ est calculée à partir des variations de porosité. Quand $\varepsilon$ dépasse le seuil $\varepsilon_0$, une loi d'endommagement exponentielle réduit la rigidité effective.</span>
<span id="cb15-59"><a href="#cb15-59" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**Diffusion de Nernst-Planck** : Le transport ionique suit la loi de diffusion couplée électro-chimique, incluant la migration sous champ électrique interne (potentiel de Donnan/diffusion $\psi$).</span>
<span id="cb15-60"><a href="#cb15-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-61"><a href="#cb15-61" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-62"><a href="#cb15-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-63"><a href="#cb15-63" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Variables et notation</span></span>
<span id="cb15-64"><a href="#cb15-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-65"><a href="#cb15-65" aria-hidden="true" tabindex="-1"></a><span class="fu">### Inconnues primaires (6 équations)</span></span>
<span id="cb15-66"><a href="#cb15-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-67"><a href="#cb15-67" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Symbole <span class="pp">|</span> Signification <span class="pp">|</span> Interne BIL <span class="pp">|</span> Inconnue BIL <span class="pp">|</span></span>
<span id="cb15-68"><a href="#cb15-68" aria-hidden="true" tabindex="-1"></a><span class="pp">|---------|---------------|-------------|--------------|</span></span>
<span id="cb15-69"><a href="#cb15-69" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\log c_{\text{SO}_4}$ <span class="pp">|</span> Log₁₀ de la concentration en sulfate <span class="pp">|</span> <span class="in">`E_Sulfur`</span> <span class="pp">|</span> <span class="in">`logc_so4`</span> <span class="pp">|</span></span>
<span id="cb15-70"><a href="#cb15-70" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\psi$ <span class="pp">|</span> Potentiel électrique diffus (V) <span class="pp">|</span> <span class="in">`E_charge`</span> <span class="pp">|</span> <span class="in">`psi`</span> <span class="pp">|</span></span>
<span id="cb15-71"><a href="#cb15-71" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $z_\text{Ca}$ <span class="pp">|</span> Quantité normalisée de calcium solide (CH) <span class="pp">|</span> <span class="in">`E_Calcium`</span> <span class="pp">|</span> <span class="in">`z_ca`</span> <span class="pp">|</span></span>
<span id="cb15-72"><a href="#cb15-72" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\log c_\text{K}$ <span class="pp">|</span> Log₁₀ de la concentration en potassium <span class="pp">|</span> <span class="in">`E_Potassium`</span> <span class="pp">|</span> <span class="in">`logc_k`</span> <span class="pp">|</span></span>
<span id="cb15-73"><a href="#cb15-73" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $z_\text{Al}$ <span class="pp">|</span> Quantité normalisée d'aluminium solide (AH₃) <span class="pp">|</span> <span class="in">`E_Aluminium`</span> <span class="pp">|</span> <span class="in">`z_al`</span> <span class="pp">|</span></span>
<span id="cb15-74"><a href="#cb15-74" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\log c_\text{OH}$ <span class="pp">|</span> Log₁₀ de la concentration en hydroxyle <span class="pp">|</span> <span class="in">`E_eneutral`</span> <span class="pp">|</span> <span class="in">`logc_oh`</span> <span class="pp">|</span></span>
<span id="cb15-75"><a href="#cb15-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-76"><a href="#cb15-76" aria-hidden="true" tabindex="-1"></a><span class="fu">### Principales variables secondaires calculées</span></span>
<span id="cb15-77"><a href="#cb15-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-78"><a href="#cb15-78" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Symbole <span class="pp">|</span> Signification <span class="pp">|</span></span>
<span id="cb15-79"><a href="#cb15-79" aria-hidden="true" tabindex="-1"></a><span class="pp">|---------|---------------|</span></span>
<span id="cb15-80"><a href="#cb15-80" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $n_\text{CH}$ <span class="pp">|</span> Teneur en moles de portlandite par litre de béton <span class="pp">|</span></span>
<span id="cb15-81"><a href="#cb15-81" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $n_\text{CSH2}$ <span class="pp">|</span> Teneur en moles de gypse (CaSO₄·2H₂O) <span class="pp">|</span></span>
<span id="cb15-82"><a href="#cb15-82" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $n_\text{AFt}$ <span class="pp">|</span> Teneur en moles d'ettringite ($\text{C}_6\text{AS}_3\text{H}_{32}$) <span class="pp">|</span></span>
<span id="cb15-83"><a href="#cb15-83" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $n_\text{AFm}$ <span class="pp">|</span> Teneur en moles de monosulfoaluminate ($\text{C}_4\text{ASH}_{12}$) <span class="pp">|</span></span>
<span id="cb15-84"><a href="#cb15-84" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $n_\text{C3AH6}$ <span class="pp">|</span> Teneur en moles d'hydrogrenat ($\text{C}_3\text{AH}_6$) <span class="pp">|</span></span>
<span id="cb15-85"><a href="#cb15-85" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\phi$ <span class="pp">|</span> Porosité instantanée (modifiée par les réactions solides) <span class="pp">|</span></span>
<span id="cb15-86"><a href="#cb15-86" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $P_c$ <span class="pp">|</span> Pression de cristallisation de l'AFt en confinement (Pa) <span class="pp">|</span></span>
<span id="cb15-87"><a href="#cb15-87" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\varepsilon$ <span class="pp">|</span> Déformation de gonflement libre <span class="pp">|</span></span>
<span id="cb15-88"><a href="#cb15-88" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $D$ <span class="pp">|</span> Variable d'endommagement ($0$ = intact, $1$ = ruiné) <span class="pp">|</span></span>
<span id="cb15-89"><a href="#cb15-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-90"><a href="#cb15-90" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-91"><a href="#cb15-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-92"><a href="#cb15-92" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4. Modèle mathématique</span></span>
<span id="cb15-93"><a href="#cb15-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-94"><a href="#cb15-94" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.1 Équations de conservation</span></span>
<span id="cb15-95"><a href="#cb15-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-96"><a href="#cb15-96" aria-hidden="true" tabindex="-1"></a>Le modèle résout six bilans de conservation couplés (Volumes Finis, <span class="in">`FVM.h`</span>) :</span>
<span id="cb15-97"><a href="#cb15-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-98"><a href="#cb15-98" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Conservation du soufre** (S, sous forme $\text{SO}_4^{2-}$ et complexes) :</span>
<span id="cb15-99"><a href="#cb15-99" aria-hidden="true" tabindex="-1"></a>   $$\frac{\partial N_S}{\partial t} + \nabla \cdot \mathbf{W}_S = 0$$</span>
<span id="cb15-100"><a href="#cb15-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-101"><a href="#cb15-101" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Conservation de la charge électrique** (électroneutralité globale) :</span>
<span id="cb15-102"><a href="#cb15-102" aria-hidden="true" tabindex="-1"></a>   $$\frac{\partial N_q}{\partial t} + \nabla \cdot \mathbf{W}_q = 0$$</span>
<span id="cb15-103"><a href="#cb15-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-104"><a href="#cb15-104" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Conservation du calcium** (dissous + solide CH + CSH + CSH₂ + AFt + AFm + C₃AH₆) :</span>
<span id="cb15-105"><a href="#cb15-105" aria-hidden="true" tabindex="-1"></a>   $$\frac{\partial N_\text{Ca}}{\partial t} + \nabla \cdot \mathbf{W}_\text{Ca} = 0$$</span>
<span id="cb15-106"><a href="#cb15-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-107"><a href="#cb15-107" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Conservation du potassium** :</span>
<span id="cb15-108"><a href="#cb15-108" aria-hidden="true" tabindex="-1"></a>   $$\frac{\partial N_K}{\partial t} + \nabla \cdot \mathbf{W}_K = 0$$</span>
<span id="cb15-109"><a href="#cb15-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-110"><a href="#cb15-110" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Conservation de l'aluminium** (dissous + solide AH₃ + AFm + AFt + C₃AH₆) :</span>
<span id="cb15-111"><a href="#cb15-111" aria-hidden="true" tabindex="-1"></a>   $$\frac{\partial N_\text{Al}}{\partial t} + \nabla \cdot \mathbf{W}_\text{Al} = 0$$</span>
<span id="cb15-112"><a href="#cb15-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-113"><a href="#cb15-113" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Electroneutralité locale** (fermeture du système) :</span>
<span id="cb15-114"><a href="#cb15-114" aria-hidden="true" tabindex="-1"></a>   $$\sum_i z_i c_i = 0$$</span>
<span id="cb15-115"><a href="#cb15-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-116"><a href="#cb15-116" aria-hidden="true" tabindex="-1"></a>où $N_x = \phi \, c_x^{\text{total}} + n_x^{\text{solide}}$ est la teneur totale (liquide + solide) par unité de volume de béton.</span>
<span id="cb15-117"><a href="#cb15-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-118"><a href="#cb15-118" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.2 Chimie de la solution interstitielle</span></span>
<span id="cb15-119"><a href="#cb15-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-120"><a href="#cb15-120" aria-hidden="true" tabindex="-1"></a>Le module <span class="in">`HardenedCementChemistry.h`</span> résout l'équilibre chimique complet de la solution de pores du béton. Les espèces considérées sont :</span>
<span id="cb15-121"><a href="#cb15-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-122"><a href="#cb15-122" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Espèce <span class="pp">|</span> Symbole <span class="pp">|</span></span>
<span id="cb15-123"><a href="#cb15-123" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------|---------|</span></span>
<span id="cb15-124"><a href="#cb15-124" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Hydroxyle <span class="pp">|</span> $\text{OH}^-$ <span class="pp">|</span></span>
<span id="cb15-125"><a href="#cb15-125" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Proton <span class="pp">|</span> $\text{H}^+$ <span class="pp">|</span></span>
<span id="cb15-126"><a href="#cb15-126" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Calcium libre <span class="pp">|</span> $\text{Ca}^{2+}$ <span class="pp">|</span></span>
<span id="cb15-127"><a href="#cb15-127" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Complexes calciques <span class="pp">|</span> $\text{CaOH}^+$ <span class="pp">|</span></span>
<span id="cb15-128"><a href="#cb15-128" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Silicates dissous <span class="pp">|</span> $\text{H}_2\text{SiO}_4^{2-}$, $\text{H}_3\text{SiO}_4^-$, $\text{H}_4\text{SiO}_4$ <span class="pp">|</span></span>
<span id="cb15-129"><a href="#cb15-129" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Complexes Ca-Si <span class="pp">|</span> $\text{CaH}_2\text{SiO}_4$, $\text{CaH}_3\text{SiO}_4^+$ <span class="pp">|</span></span>
<span id="cb15-130"><a href="#cb15-130" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Sulfates <span class="pp">|</span> $\text{SO}_4^{2-}$, $\text{HSO}_4^-$, $\text{H}_2\text{SO}_4$ <span class="pp">|</span></span>
<span id="cb15-131"><a href="#cb15-131" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Complexes Ca-sulfate <span class="pp">|</span> $\text{CaSO}_4^\text{aq}$, $\text{CaHSO}_4^+$ <span class="pp">|</span></span>
<span id="cb15-132"><a href="#cb15-132" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Potassium <span class="pp">|</span> $\text{K}^+$, $\text{KOH}^\text{aq}$ <span class="pp">|</span></span>
<span id="cb15-133"><a href="#cb15-133" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Aluminates <span class="pp">|</span> $\text{Al}(\text{OH})_4^-$ <span class="pp">|</span></span>
<span id="cb15-134"><a href="#cb15-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-135"><a href="#cb15-135" aria-hidden="true" tabindex="-1"></a>Ces concentrations sont toutes dérivées des 6 inconnues primaires via les constantes d'équilibre thermodynamique à $T = 293\,\text{K}$.</span>
<span id="cb15-136"><a href="#cb15-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-137"><a href="#cb15-137" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.3 Réactions avec les phases solides</span></span>
<span id="cb15-138"><a href="#cb15-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-139"><a href="#cb15-139" aria-hidden="true" tabindex="-1"></a>Les phases solides se dissolvent ou précipitent selon leur état de saturation :</span>
<span id="cb15-140"><a href="#cb15-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-141"><a href="#cb15-141" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Portlandite — $\text{CH} = \text{Ca(OH)}_2$</span></span>
<span id="cb15-142"><a href="#cb15-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-143"><a href="#cb15-143" aria-hidden="true" tabindex="-1"></a>Dissolution contrôlée par le bilan de calcium solide :</span>
<span id="cb15-144"><a href="#cb15-144" aria-hidden="true" tabindex="-1"></a>$$n_\text{CH} = N_\text{CH}^{\text{ref}} \cdot \max(z_\text{Ca}, 0)$$</span>
<span id="cb15-145"><a href="#cb15-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-146"><a href="#cb15-146" aria-hidden="true" tabindex="-1"></a>La variable $z_\text{Ca}$ décroît quand le calcium solide est consommé par les sulfates ou lixivié.</span>
<span id="cb15-147"><a href="#cb15-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-148"><a href="#cb15-148" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Gypse — $\text{CSH}_2 = \text{CaSO}_4 \cdot 2\text{H}_2\text{O}$ (Cinétique)</span></span>
<span id="cb15-149"><a href="#cb15-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-150"><a href="#cb15-150" aria-hidden="true" tabindex="-1"></a>$$n_\text{CSH2}(t+\Delta t) = \max<span class="sc">\!</span>\left(n_\text{CSH2}(t) + \Delta t \cdot R_\text{CSH2} \cdot (S_\text{CSH2} - 1),\, 0\right)$$</span>
<span id="cb15-151"><a href="#cb15-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-152"><a href="#cb15-152" aria-hidden="true" tabindex="-1"></a>où $S_\text{CSH2}$ est l'indice de saturation (rapport activité/produit de solubilité) et $R_\text{CSH2}$ le taux cinétique.</span>
<span id="cb15-153"><a href="#cb15-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-154"><a href="#cb15-154" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Ettringite — $\text{AFt} = \text{C}_6\text{AS}_3\text{H}_{32}$ (Cinétique avec confinement)</span></span>
<span id="cb15-155"><a href="#cb15-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-156"><a href="#cb15-156" aria-hidden="true" tabindex="-1"></a>La cinétique de précipitation de l'AFt est plus élaborée : elle distingue la **croissance en interface libre** (paroi de pore) et la **croissance en confinement** (pore rempli), cette dernière générant une pression :</span>
<span id="cb15-157"><a href="#cb15-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-158"><a href="#cb15-158" aria-hidden="true" tabindex="-1"></a>$$n_\text{AFt}(t+\Delta t) = \max<span class="sc">\!</span>\left(n_\text{AFt}(t) + \Delta t \cdot R_\text{AFt} \cdot f(\beta, \beta_p),\, 0\right)$$</span>
<span id="cb15-159"><a href="#cb15-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-160"><a href="#cb15-160" aria-hidden="true" tabindex="-1"></a>où $\beta = S_\text{AFt}$ (indice de sursaturation global) et $\beta_p$ est l'indice d'équilibre au niveau de l'interface cristal-liquide confiné.</span>
<span id="cb15-161"><a href="#cb15-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-162"><a href="#cb15-162" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Monosulfoaluminate — $\text{AFm} = \text{C}_4\text{ASH}_{12}$ et Hydrogrenat — $\text{C}_3\text{AH}_6$ (Cinétique)</span></span>
<span id="cb15-163"><a href="#cb15-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-164"><a href="#cb15-164" aria-hidden="true" tabindex="-1"></a>$$n_x(t+\Delta t) = \max<span class="sc">\!</span>\left(n_x(t) + \Delta t \cdot R_x \cdot (S_x - 1),\, 0\right)$$</span>
<span id="cb15-165"><a href="#cb15-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-166"><a href="#cb15-166" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.4 Pression de cristallisation et endommagement</span></span>
<span id="cb15-167"><a href="#cb15-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-168"><a href="#cb15-168" aria-hidden="true" tabindex="-1"></a>Lorsque l'AFt précipite dans un pore de rayon $r$, il génère une surpression donnée par la relation de **Kelvin-Thomson** :</span>
<span id="cb15-169"><a href="#cb15-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-170"><a href="#cb15-170" aria-hidden="true" tabindex="-1"></a>$$P_c = \frac{RT}{V_\text{AFt}} \ln(\beta)$$</span>
<span id="cb15-171"><a href="#cb15-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-172"><a href="#cb15-172" aria-hidden="true" tabindex="-1"></a>où $\beta$ est l'indice de sursaturation de l'AFt par rapport à l'équilibre confiné et $V_\text{AFt} = 710.32\,\text{cm}^3/\text{mol}$ est le volume molaire de l'ettringite.</span>
<span id="cb15-173"><a href="#cb15-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-174"><a href="#cb15-174" aria-hidden="true" tabindex="-1"></a>L'équilibre thermodynamique à l'interface cristal-liquide dans un pore de rayon $r$ est :</span>
<span id="cb15-175"><a href="#cb15-175" aria-hidden="true" tabindex="-1"></a>$$\beta_\text{eq}(r) = \exp<span class="sc">\!</span>\left(\frac{2\,\Gamma_\text{AFt}\,V_\text{AFt}}{RT \cdot r}\right)$$</span>
<span id="cb15-176"><a href="#cb15-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-177"><a href="#cb15-177" aria-hidden="true" tabindex="-1"></a>avec $\Gamma_\text{AFt} = 0.1\,\text{N/m}$ la tension superficielle.</span>
<span id="cb15-178"><a href="#cb15-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-179"><a href="#cb15-179" aria-hidden="true" tabindex="-1"></a>La pression de cristallisation volumétriquement intégrée produit une **déformation de gonflement libre** $\varepsilon$. Quand $\varepsilon$ dépasse le seuil $\varepsilon_0$, le béton s'endommage selon une loi exponentielle :</span>
<span id="cb15-180"><a href="#cb15-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-181"><a href="#cb15-181" aria-hidden="true" tabindex="-1"></a>$$D(\varepsilon) = 1 - \frac{\varepsilon_0}{\varepsilon} \exp<span class="sc">\!</span>\left(-\frac{\varepsilon - \varepsilon_0}{\varepsilon_f}\right)$$</span>
<span id="cb15-182"><a href="#cb15-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-183"><a href="#cb15-183" aria-hidden="true" tabindex="-1"></a>où $\varepsilon_0$ est la déformation seuil et $\varepsilon_f$ la déformation caractéristique de rupture. L'endommagement $D$ réduit la contrainte effective et augmente la perméabilité aux ions.</span>
<span id="cb15-184"><a href="#cb15-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-185"><a href="#cb15-185" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.5 Loi de transport (diffusion ionique)</span></span>
<span id="cb15-186"><a href="#cb15-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-187"><a href="#cb15-187" aria-hidden="true" tabindex="-1"></a>Le flux de chaque ion $i$ (de charge $z_i$ et coefficient de diffusion $D_i$) dans la solution de pores est donné par l'équation de **Nernst-Planck** :</span>
<span id="cb15-188"><a href="#cb15-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-189"><a href="#cb15-189" aria-hidden="true" tabindex="-1"></a>$$\mathbf{W}_i = -\phi \, \tau(\phi) \left( D_i \nabla c_i + z_i \frac{F D_i}{RT} c_i \nabla \psi \right)$$</span>
<span id="cb15-190"><a href="#cb15-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-191"><a href="#cb15-191" aria-hidden="true" tabindex="-1"></a>où $\tau(\phi)$ est la tortuosité effective selon la loi de Bazant-Najjar :</span>
<span id="cb15-192"><a href="#cb15-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-193"><a href="#cb15-193" aria-hidden="true" tabindex="-1"></a>$$\tau(\phi) = 0.001 + 0.07\phi^2 + H(\phi - 0.18) \cdot 1.8(\phi - 0.18)^2$$</span>
<span id="cb15-194"><a href="#cb15-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-195"><a href="#cb15-195" aria-hidden="true" tabindex="-1"></a>Le module <span class="in">`CementSolutionDiffusion.h`</span> gère les coefficients $D_i$ pour chaque ion.</span>
<span id="cb15-196"><a href="#cb15-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-197"><a href="#cb15-197" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-198"><a href="#cb15-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-199"><a href="#cb15-199" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5. Conditions aux limites et initiales</span></span>
<span id="cb15-200"><a href="#cb15-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-201"><a href="#cb15-201" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conditions initiales</span></span>
<span id="cb15-202"><a href="#cb15-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-203"><a href="#cb15-203" aria-hidden="true" tabindex="-1"></a>Le béton est initialement dans un état d'équilibre chimique "intact" défini par les teneurs initiales en phases solides ($N_\text{CH}$, $N_\text{CSH}$, $N_\text{C3AH6}$...) et une concentration en sulfates très faible ($\log c_{\text{SO}_4} = -6$, soit $c_{\text{SO}_4} = 10^{-6}\,\text{mol/L}$).</span>
<span id="cb15-204"><a href="#cb15-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-205"><a href="#cb15-205" aria-hidden="true" tabindex="-1"></a><span class="fu">### Conditions aux limites</span></span>
<span id="cb15-206"><a href="#cb15-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-207"><a href="#cb15-207" aria-hidden="true" tabindex="-1"></a>Le système est **exposé d'un côté** (région 1, $x=0$) à une solution sulfatée dont la concentration en $\text{SO}_4^{2-}$ augmente au cours du temps selon les fonctions définies dans le fichier d'entrée. L'autre face (région 3, $x=L$) est laissée sans flux (Neumann nul implicite).</span>
<span id="cb15-208"><a href="#cb15-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-209"><a href="#cb15-209" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-210"><a href="#cb15-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-211"><a href="#cb15-211" aria-hidden="true" tabindex="-1"></a><span class="fu">## 6. Cas test : Attaque sulfatique d'un échantillon de béton (`base/Sulfaco/`)</span></span>
<span id="cb15-212"><a href="#cb15-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-213"><a href="#cb15-213" aria-hidden="true" tabindex="-1"></a><span class="fu">### Géométrie</span></span>
<span id="cb15-214"><a href="#cb15-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-215"><a href="#cb15-215" aria-hidden="true" tabindex="-1"></a>L'échantillon est un **domaine 1D de longueur $L = 1\,\text{dm}$**, discrétisé en un seul élément fini de volumes finis avec deux nœuds (représentation d'un "point matériel" homogène sans gradient spatial interne).</span>
<span id="cb15-216"><a href="#cb15-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-217"><a href="#cb15-217" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scénario simulé</span></span>
<span id="cb15-218"><a href="#cb15-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-219"><a href="#cb15-219" aria-hidden="true" tabindex="-1"></a>Il s'agit d'une simulation d'un **point de matériau unique** (pas de gradient spatial) exposé à un apport croissant de sulfates. Les concentrations imposées en $x=0$ varient selon des fonctions temporelles définies dans le fichier d'entrée :</span>
<span id="cb15-220"><a href="#cb15-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-221"><a href="#cb15-221" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Variable imposée <span class="pp">|</span> $t=0$ <span class="pp">|</span> $t=8640\,\text{s}$ <span class="pp">|</span> $t=864000\,\text{s}$ <span class="pp">|</span></span>
<span id="cb15-222"><a href="#cb15-222" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------------|-------|--------|---------|</span></span>
<span id="cb15-223"><a href="#cb15-223" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\log c_{\text{SO}_4}$ <span class="pp">|</span> $-6$ <span class="pp">|</span> $-2.556$ <span class="pp">|</span> $-0.456$ <span class="pp">|</span></span>
<span id="cb15-224"><a href="#cb15-224" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\log c_K$ <span class="pp">|</span> $-5.7$ <span class="pp">|</span> $-2.256$ <span class="pp">|</span> $-0.156$ <span class="pp">|</span></span>
<span id="cb15-225"><a href="#cb15-225" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> $\log c_\text{OH}$ <span class="pp">|</span> $-2$ (pH 12) <span class="pp">|</span> $-2$ <span class="pp">|</span> $-2$ <span class="pp">|</span></span>
<span id="cb15-226"><a href="#cb15-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-227"><a href="#cb15-227" aria-hidden="true" tabindex="-1"></a>La durée totale simulée est de $3.5 \times 10^6\,\text{s} \approx 40\,\text{jours}$.</span>
<span id="cb15-228"><a href="#cb15-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-229"><a href="#cb15-229" aria-hidden="true" tabindex="-1"></a><span class="fu">### Résultats attendus (sorties `.gp`)</span></span>
<span id="cb15-230"><a href="#cb15-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-231"><a href="#cb15-231" aria-hidden="true" tabindex="-1"></a>Le fichier Gnuplot <span class="in">`Sulfaco.gp`</span> trace neuf figures de post-traitement :</span>
<span id="cb15-232"><a href="#cb15-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-233"><a href="#cb15-233" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Figure <span class="pp">|</span> Fichier <span class="pp">|</span> Contenu physique <span class="pp">|</span></span>
<span id="cb15-234"><a href="#cb15-234" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------|---------|-----------------|</span></span>
<span id="cb15-235"><a href="#cb15-235" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> <span class="in">`Strain.eps`</span> <span class="pp">|</span> Déformation de gonflement $\varepsilon(t)$ <span class="pp">|</span></span>
<span id="cb15-236"><a href="#cb15-236" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> <span class="in">`EttringiteSaturationIndex.eps`</span> <span class="pp">|</span> Indice de saturation $S_\text{AFt}(t)$ (log-log) <span class="pp">|</span></span>
<span id="cb15-237"><a href="#cb15-237" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> <span class="in">`EttringiteContent.eps`</span> <span class="pp">|</span> Teneur en ettringite $n_\text{AFt}(t)$ (mol/L de béton) <span class="pp">|</span></span>
<span id="cb15-238"><a href="#cb15-238" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> <span class="in">`CrystallizationPressure.eps`</span> <span class="pp">|</span> Pression de cristallisation $P_c(t)$ (Pa) <span class="pp">|</span></span>
<span id="cb15-239"><a href="#cb15-239" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> <span class="in">`pH.eps`</span> <span class="pp">|</span> Évolution du pH de la solution interstitielle <span class="pp">|</span></span>
<span id="cb15-240"><a href="#cb15-240" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 6 <span class="pp">|</span> <span class="in">`SaturationIndexes.eps`</span> <span class="pp">|</span> Indices de saturation : AFt et gypse (CSH₂) <span class="pp">|</span></span>
<span id="cb15-241"><a href="#cb15-241" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 7 <span class="pp">|</span> <span class="in">`SolidContents.eps`</span> <span class="pp">|</span> Évolution des phases solides : CH, AFt, C₃AH₆ <span class="pp">|</span></span>
<span id="cb15-242"><a href="#cb15-242" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 8 <span class="pp">|</span> <span class="in">`IonConcentrations.eps`</span> <span class="pp">|</span> Concentration en $\text{SO}_4^{2-}$ (mol/L) <span class="pp">|</span></span>
<span id="cb15-243"><a href="#cb15-243" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 9 <span class="pp">|</span> <span class="in">`StressStrain.eps`</span> <span class="pp">|</span> Contrainte effective $S_c \cdot P_c$ vs. déformation <span class="pp">|</span></span>
<span id="cb15-244"><a href="#cb15-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-245"><a href="#cb15-245" aria-hidden="true" tabindex="-1"></a>La séquence physique attendue est :</span>
<span id="cb15-246"><a href="#cb15-246" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Les sulfates entrant réagissent d'abord avec **C₃AH₆** (hydrogrenat) et **AFm** (monosulfoaluminate), qui se convertissent en **AFt** (ettringite).</span>
<span id="cb15-247"><a href="#cb15-247" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>L'indice de saturation de l'AFt croît, la **pression de cristallisation** augmente.</span>
<span id="cb15-248"><a href="#cb15-248" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Quand $P_c$ dépasse la résistance à la traction (déformation $\varepsilon &gt; \varepsilon_0$), **l'endommagement** $D$ s'enclenche et la déformation libre $\varepsilon$ augmente brutalement.</span>
<span id="cb15-249"><a href="#cb15-249" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>La **portlandite** (CH) se dissout progressivement, tamponnant le pH.</span>
<span id="cb15-250"><a href="#cb15-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-251"><a href="#cb15-251" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-252"><a href="#cb15-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-253"><a href="#cb15-253" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7. Paramétrage matériel du modèle</span></span>
<span id="cb15-254"><a href="#cb15-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-255"><a href="#cb15-255" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Paramètre <span class="pp">|</span> Valeur dans <span class="in">`Sulfaco`</span> <span class="pp">|</span> Rôle physique <span class="pp">|</span></span>
<span id="cb15-256"><a href="#cb15-256" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------|----------------------|---------------|</span></span>
<span id="cb15-257"><a href="#cb15-257" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`porosity`</span> <span class="pp">|</span> $0.23$ <span class="pp">|</span> Porosité initiale du béton sain <span class="pp">|</span></span>
<span id="cb15-258"><a href="#cb15-258" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`N_CH`</span> <span class="pp">|</span> $1.53\,\text{mol/L}$ <span class="pp">|</span> Teneur initiale en portlandite <span class="pp">|</span></span>
<span id="cb15-259"><a href="#cb15-259" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`N_CSH`</span> <span class="pp">|</span> $1.393\,\text{mol/L}$ <span class="pp">|</span> Teneur initiale en C-S-H (source Si) <span class="pp">|</span></span>
<span id="cb15-260"><a href="#cb15-260" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`N_AH3`</span> <span class="pp">|</span> $10^{-6}\,\text{mol/L}$ <span class="pp">|</span> Gibbsite (quasi-nul, trace) <span class="pp">|</span></span>
<span id="cb15-261"><a href="#cb15-261" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`N_C3AH6`</span> <span class="pp">|</span> $0.2\,\text{mol/L}$ <span class="pp">|</span> Hydrogrenat initial (précurseur aluminium) <span class="pp">|</span></span>
<span id="cb15-262"><a href="#cb15-262" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`N_CSH2`</span>, <span class="in">`N_AFm`</span>, <span class="in">`N_AFt`</span> <span class="pp">|</span> $0$ <span class="pp">|</span> Pas de gypse ni ettringite initiale <span class="pp">|</span></span>
<span id="cb15-263"><a href="#cb15-263" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`R_CSH2`</span> <span class="pp">|</span> $10^{-12}\,\text{mol/L/s}$ <span class="pp">|</span> Taux de précipitation du gypse (très lent) <span class="pp">|</span></span>
<span id="cb15-264"><a href="#cb15-264" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`R_AFm`</span> <span class="pp">|</span> $10^{-6}\,\text{mol/L/s}$ <span class="pp">|</span> Taux de précipitation du monosulfoaluminate <span class="pp">|</span></span>
<span id="cb15-265"><a href="#cb15-265" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`R_C3AH6`</span> <span class="pp">|</span> $10^{-6}\,\text{mol/L/s}$ <span class="pp">|</span> Taux de dissolution de l'hydrogrenat <span class="pp">|</span></span>
<span id="cb15-266"><a href="#cb15-266" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`A_i`</span> <span class="pp">|</span> $8.4 \times 10^{-8}$ <span class="pp">|</span> Taux de croissance de l'AFt en interface libre ($a_r$) <span class="pp">|</span></span>
<span id="cb15-267"><a href="#cb15-267" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`A_p`</span> <span class="pp">|</span> $4.4 \times 10^{-9}$ <span class="pp">|</span> Taux de croissance de l'AFt en pore confiné ($a_p$) <span class="pp">|</span></span>
<span id="cb15-268"><a href="#cb15-268" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`K_bulk`</span> <span class="pp">|</span> $30.1\,\text{GPa}$ <span class="pp">|</span> Module de compression du béton sain <span class="pp">|</span></span>
<span id="cb15-269"><a href="#cb15-269" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`Biot`</span> <span class="pp">|</span> $0.54$ <span class="pp">|</span> Coefficient de Biot (couplage pression-déformation) <span class="pp">|</span></span>
<span id="cb15-270"><a href="#cb15-270" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`Strain0`</span> <span class="pp">|</span> $4 \times 10^{-4}$ <span class="pp">|</span> Déformation seuil d'endommagement $\varepsilon_0$ <span class="pp">|</span></span>
<span id="cb15-271"><a href="#cb15-271" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`Strainf`</span> <span class="pp">|</span> $6.4 \times 10^{-3}$ <span class="pp">|</span> Déformation caractéristique de rupture $\varepsilon_f$ <span class="pp">|</span></span>
<span id="cb15-272"><a href="#cb15-272" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`AlphaCoef`</span> <span class="pp">|</span> $0$ <span class="pp">|</span> Coefficient d'adsorption des sulfates sur les C-S-H (désactivé) <span class="pp">|</span></span>
<span id="cb15-273"><a href="#cb15-273" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`BetaCoef`</span> <span class="pp">|</span> $0.87$ <span class="pp">|</span> Coefficient de saturation dans l'isotherme d'adsorption <span class="pp">|</span></span>
<span id="cb15-274"><a href="#cb15-274" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`Curves_log = Sat`</span> <span class="pp">|</span> Van Genuchten ($m=0.2516$, $r_0=155.82\,\text{nm}$) <span class="pp">|</span> Courbe de saturation liquide $S_r(r)$ dans les pores <span class="pp">|</span></span>
<span id="cb15-275"><a href="#cb15-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-276"><a href="#cb15-276" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-277"><a href="#cb15-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-278"><a href="#cb15-278" aria-hidden="true" tabindex="-1"></a><span class="fu">## 8. Description pas-à-pas des fichiers d'entrée</span></span>
<span id="cb15-279"><a href="#cb15-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-280"><a href="#cb15-280" aria-hidden="true" tabindex="-1"></a><span class="fu">### 8.1 Système d'unités (`Units`)</span></span>
<span id="cb15-281"><a href="#cb15-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-282"><a href="#cb15-282" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-283"><a href="#cb15-283" aria-hidden="true" tabindex="-1"></a><span class="in">Units</span></span>
<span id="cb15-284"><a href="#cb15-284" aria-hidden="true" tabindex="-1"></a><span class="in">Length = decimeter     # 1 unité de longueur = 1 dm</span></span>
<span id="cb15-285"><a href="#cb15-285" aria-hidden="true" tabindex="-1"></a><span class="in">Time   = second        # 1 unité de temps = 1 s</span></span>
<span id="cb15-286"><a href="#cb15-286" aria-hidden="true" tabindex="-1"></a><span class="in">Mass   = hectogram     # 1 unité de masse = 100 g</span></span>
<span id="cb15-287"><a href="#cb15-287" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-288"><a href="#cb15-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-289"><a href="#cb15-289" aria-hidden="true" tabindex="-1"></a>Le choix du décimètre comme unité de longueur est cohérent avec les tailles d'éprouvettes de béton (quelques centimètres à décimètres). Les concentrations sont donc en **mol/dm³ = mol/L** et les diffusivités en **dm²/s**.</span>
<span id="cb15-290"><a href="#cb15-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-291"><a href="#cb15-291" aria-hidden="true" tabindex="-1"></a><span class="fu">### 8.2 Géométrie et maillage (`Geometry`, `Mesh`)</span></span>
<span id="cb15-292"><a href="#cb15-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-293"><a href="#cb15-293" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-294"><a href="#cb15-294" aria-hidden="true" tabindex="-1"></a><span class="in">Geometry</span></span>
<span id="cb15-295"><a href="#cb15-295" aria-hidden="true" tabindex="-1"></a><span class="in">Dimension = 1  plan     # Problème 1D en coordonnées planes (cartésiennes)</span></span>
<span id="cb15-296"><a href="#cb15-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-297"><a href="#cb15-297" aria-hidden="true" tabindex="-1"></a><span class="in">Mesh</span></span>
<span id="cb15-298"><a href="#cb15-298" aria-hidden="true" tabindex="-1"></a><span class="in">2                        # 2 nœuds</span></span>
<span id="cb15-299"><a href="#cb15-299" aria-hidden="true" tabindex="-1"></a><span class="in">0. 1                     # Nœud 1 : x=0 (surface exposée)</span></span>
<span id="cb15-300"><a href="#cb15-300" aria-hidden="true" tabindex="-1"></a><span class="in">1.                       # Nœud 2 : x=1 dm (cœur)</span></span>
<span id="cb15-301"><a href="#cb15-301" aria-hidden="true" tabindex="-1"></a><span class="in">1                        # 1 élément</span></span>
<span id="cb15-302"><a href="#cb15-302" aria-hidden="true" tabindex="-1"></a><span class="in">1                        # Élément linéaire reliant nœuds 1-2 (région 1)</span></span>
<span id="cb15-303"><a href="#cb15-303" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-304"><a href="#cb15-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-305"><a href="#cb15-305" aria-hidden="true" tabindex="-1"></a>Le fichier maillage <span class="in">`Sulfaco.msh`</span> (format Gmsh) définit explicitement 4 nœuds dont 2 nœuds de bord (type 15 = points) et 1 segment (type 1) entre $x=0$ et $x=1\,\text{dm}$.</span>
<span id="cb15-306"><a href="#cb15-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-307"><a href="#cb15-307" aria-hidden="true" tabindex="-1"></a><span class="fu">### 8.3 Matériau (`Material`)</span></span>
<span id="cb15-308"><a href="#cb15-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-309"><a href="#cb15-309" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-310"><a href="#cb15-310" aria-hidden="true" tabindex="-1"></a><span class="in">Model = Sulfaco</span></span>
<span id="cb15-311"><a href="#cb15-311" aria-hidden="true" tabindex="-1"></a><span class="in">porosity = 0.23</span></span>
<span id="cb15-312"><a href="#cb15-312" aria-hidden="true" tabindex="-1"></a><span class="in">N_CH     = 1.53</span></span>
<span id="cb15-313"><a href="#cb15-313" aria-hidden="true" tabindex="-1"></a><span class="in">N_CSH    = 1.393</span></span>
<span id="cb15-314"><a href="#cb15-314" aria-hidden="true" tabindex="-1"></a><span class="in">N_AH3    = 1.e-6</span></span>
<span id="cb15-315"><a href="#cb15-315" aria-hidden="true" tabindex="-1"></a><span class="in">N_C3AH6  = 0.2</span></span>
<span id="cb15-316"><a href="#cb15-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-317"><a href="#cb15-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-318"><a href="#cb15-318" aria-hidden="true" tabindex="-1"></a>Ces lignes définissent la **microstructure initiale** du béton : portlandite et C-S-H sont les réservoirs de calcium qui contrôlent le tampon pH et la source de calcium pour les réactions sulfatiques.</span>
<span id="cb15-319"><a href="#cb15-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-320"><a href="#cb15-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-321"><a href="#cb15-321" aria-hidden="true" tabindex="-1"></a><span class="in">R_CSH2   = 1.e-12</span></span>
<span id="cb15-322"><a href="#cb15-322" aria-hidden="true" tabindex="-1"></a><span class="in">R_AFm    = 1.e-6</span></span>
<span id="cb15-323"><a href="#cb15-323" aria-hidden="true" tabindex="-1"></a><span class="in">R_C3AH6  = 1.e-6</span></span>
<span id="cb15-324"><a href="#cb15-324" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-325"><a href="#cb15-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-326"><a href="#cb15-326" aria-hidden="true" tabindex="-1"></a>Ces constantes cinétiques (<span class="in">`R_x`</span>, en mol/L/s) contrôlent la vitesse des transformations solides. <span class="in">`R_CSH2`</span> très petit signifie que le gypse précipite très lentement ; <span class="in">`R_C3AH6`</span> modéré permet une dissolution rapide de l'hydrogrenat en ettringite.</span>
<span id="cb15-327"><a href="#cb15-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-328"><a href="#cb15-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-329"><a href="#cb15-329" aria-hidden="true" tabindex="-1"></a><span class="in">A_i = 8.4e-8</span></span>
<span id="cb15-330"><a href="#cb15-330" aria-hidden="true" tabindex="-1"></a><span class="in">A_p = 4.4e-9</span></span>
<span id="cb15-331"><a href="#cb15-331" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-332"><a href="#cb15-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-333"><a href="#cb15-333" aria-hidden="true" tabindex="-1"></a>Coefficients de cinétique de croissance cristalline de l'AFt : <span class="in">`A_i`</span> (interface libre, rapide) et <span class="in">`A_p`</span> (pore confiné, 20 fois plus lent).</span>
<span id="cb15-334"><a href="#cb15-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-335"><a href="#cb15-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-336"><a href="#cb15-336" aria-hidden="true" tabindex="-1"></a><span class="in">K_bulk = 30.1e9</span></span>
<span id="cb15-337"><a href="#cb15-337" aria-hidden="true" tabindex="-1"></a><span class="in">Biot = 0.54</span></span>
<span id="cb15-338"><a href="#cb15-338" aria-hidden="true" tabindex="-1"></a><span class="in">Strain0 = 4.e-4</span></span>
<span id="cb15-339"><a href="#cb15-339" aria-hidden="true" tabindex="-1"></a><span class="in">Strainf = 6.4e-3</span></span>
<span id="cb15-340"><a href="#cb15-340" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-341"><a href="#cb15-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-342"><a href="#cb15-342" aria-hidden="true" tabindex="-1"></a>Paramètres mécaniques : le module de compression $K_\text{bulk}$ et le coefficient de Biot permettent de calculer la contrainte effective. <span class="in">`Strain0`</span> et <span class="in">`Strainf`</span> définissent la courbe d'endommagement : le béton commence à se fissurer à partir d'une déformation de $4 \times 10^{-4}$ et est totalement ruiné à $\sim 7 \times 10^{-3}$.</span>
<span id="cb15-343"><a href="#cb15-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-344"><a href="#cb15-344" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-345"><a href="#cb15-345" aria-hidden="true" tabindex="-1"></a><span class="in">Curves_log = Sat  r = Range{r1 = 1.e-8 , r2 = 1.e-3 , n = 1000}</span></span>
<span id="cb15-346"><a href="#cb15-346" aria-hidden="true" tabindex="-1"></a><span class="in">             S_r = Expressions(1){r0=155.82e-8; m = 0.2516 ; S_r = (1 + (r0/r)**(1/(1-m)))**(-m)}</span></span>
<span id="cb15-347"><a href="#cb15-347" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-348"><a href="#cb15-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-349"><a href="#cb15-349" aria-hidden="true" tabindex="-1"></a>Courbe de saturation de van Genuchten : pour un rayon de pore $r$ (en m), $S_r(r)$ donne la fraction de pores plus petits que $r$ saturés en solution. Elle est tabulée sur 1000 points entre $r=10\,\text{nm}$ et $r=1\,\text{mm}$.</span>
<span id="cb15-350"><a href="#cb15-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-351"><a href="#cb15-351" aria-hidden="true" tabindex="-1"></a><span class="fu">### 8.4 Champs (`Fields`)</span></span>
<span id="cb15-352"><a href="#cb15-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-353"><a href="#cb15-353" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-354"><a href="#cb15-354" aria-hidden="true" tabindex="-1"></a><span class="in">Fields</span></span>
<span id="cb15-355"><a href="#cb15-355" aria-hidden="true" tabindex="-1"></a><span class="in">1</span></span>
<span id="cb15-356"><a href="#cb15-356" aria-hidden="true" tabindex="-1"></a><span class="in">Value = 1   Gradient = 0 0 0   Point = 0 0 0</span></span>
<span id="cb15-357"><a href="#cb15-357" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-358"><a href="#cb15-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-359"><a href="#cb15-359" aria-hidden="true" tabindex="-1"></a>Un seul champ scalaire uniforme (valeur 1, gradient nul) est défini. Il sert comme **multiplicateur** dans les fonctions d'initialisation et de conditions aux limites.</span>
<span id="cb15-360"><a href="#cb15-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-361"><a href="#cb15-361" aria-hidden="true" tabindex="-1"></a><span class="fu">### 8.5 Initialisation (`Initialization`)</span></span>
<span id="cb15-362"><a href="#cb15-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-363"><a href="#cb15-363" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-364"><a href="#cb15-364" aria-hidden="true" tabindex="-1"></a><span class="in">Initialization</span></span>
<span id="cb15-365"><a href="#cb15-365" aria-hidden="true" tabindex="-1"></a><span class="in">6</span></span>
<span id="cb15-366"><a href="#cb15-366" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = logc_so4   Field = 1 Function = 1</span></span>
<span id="cb15-367"><a href="#cb15-367" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = psi        Field = 0 Function = 0</span></span>
<span id="cb15-368"><a href="#cb15-368" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = z_ca       Field = 1 Function = 4</span></span>
<span id="cb15-369"><a href="#cb15-369" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = z_al       Field = 1 Function = 3</span></span>
<span id="cb15-370"><a href="#cb15-370" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = logc_k     Field = 1 Function = 2</span></span>
<span id="cb15-371"><a href="#cb15-371" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = logc_oh    Field = 1 Function = 5</span></span>
<span id="cb15-372"><a href="#cb15-372" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-373"><a href="#cb15-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-374"><a href="#cb15-374" aria-hidden="true" tabindex="-1"></a>Chaque ligne initialise une inconnue dans la région 1 (tout le domaine) à la valeur <span class="in">`Field × Function(t=0)`</span> :</span>
<span id="cb15-375"><a href="#cb15-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-376"><a href="#cb15-376" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Inconnue <span class="pp">|</span> Valeur initiale <span class="pp">|</span> Signification <span class="pp">|</span></span>
<span id="cb15-377"><a href="#cb15-377" aria-hidden="true" tabindex="-1"></a><span class="pp">|----------|----------------|---------------|</span></span>
<span id="cb15-378"><a href="#cb15-378" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`logc_so4`</span> <span class="pp">|</span> $1 \times (-6) = -6$ <span class="pp">|</span> $c_{\text{SO}_4} = 10^{-6}\,\text{mol/L}$ (béton sain, peu de sulfates) <span class="pp">|</span></span>
<span id="cb15-379"><a href="#cb15-379" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`psi`</span> <span class="pp">|</span> $0 \times 0 = 0$ <span class="pp">|</span> Potentiel électrique nul à l'état initial <span class="pp">|</span></span>
<span id="cb15-380"><a href="#cb15-380" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`z_ca`</span> <span class="pp">|</span> $1 \times 1 = 1$ <span class="pp">|</span> Portlandite intacte : $n_\text{CH} = N_\text{CH} \times 1$ <span class="pp">|</span></span>
<span id="cb15-381"><a href="#cb15-381" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`z_al`</span> <span class="pp">|</span> $1 \times 1 = 1$ <span class="pp">|</span> AH₃ solide intact : $n_\text{AH3} = N_\text{AH3} \times 1$ <span class="pp">|</span></span>
<span id="cb15-382"><a href="#cb15-382" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`logc_k`</span> <span class="pp">|</span> $1 \times (-5.7) = -5.7$ <span class="pp">|</span> $c_K \approx 2 \times 10^{-6}\,\text{mol/L}$ <span class="pp">|</span></span>
<span id="cb15-383"><a href="#cb15-383" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`logc_oh`</span> <span class="pp">|</span> $1 \times (-2) = -2$ <span class="pp">|</span> pH $= 12$ ($c_{\text{OH}^-} = 10^{-2}\,\text{mol/L}$) <span class="pp">|</span></span>
<span id="cb15-384"><a href="#cb15-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-385"><a href="#cb15-385" aria-hidden="true" tabindex="-1"></a><span class="fu">### 8.6 Fonctions temporelles (`Functions`)</span></span>
<span id="cb15-386"><a href="#cb15-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-387"><a href="#cb15-387" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-388"><a href="#cb15-388" aria-hidden="true" tabindex="-1"></a><span class="in">Functions</span></span>
<span id="cb15-389"><a href="#cb15-389" aria-hidden="true" tabindex="-1"></a><span class="in">5</span></span>
<span id="cb15-390"><a href="#cb15-390" aria-hidden="true" tabindex="-1"></a><span class="in">N = 5 F(0) = -6     F(8640) = -2.556  F(86400) = -1.556  F(345600) = -0.954  F(864000) = -0.456</span></span>
<span id="cb15-391"><a href="#cb15-391" aria-hidden="true" tabindex="-1"></a><span class="in">N = 5 F(0) = -5.7   F(8640) = -2.256  F(86400) = -1.256  F(345600) = -0.654  F(864000) = -0.156</span></span>
<span id="cb15-392"><a href="#cb15-392" aria-hidden="true" tabindex="-1"></a><span class="in">N = 2 F(0) = -7.32  F(86400) = -6.32</span></span>
<span id="cb15-393"><a href="#cb15-393" aria-hidden="true" tabindex="-1"></a><span class="in">N = 2 F(0) = 1      F(86400) = 1</span></span>
<span id="cb15-394"><a href="#cb15-394" aria-hidden="true" tabindex="-1"></a><span class="in">N = 2 F(0) = -2     F(86400) = -2</span></span>
<span id="cb15-395"><a href="#cb15-395" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-396"><a href="#cb15-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-397"><a href="#cb15-397" aria-hidden="true" tabindex="-1"></a>Cinq fonctions d'interpolation temporelle linéaire par morceaux (avec <span class="in">`N`</span> points) :</span>
<span id="cb15-398"><a href="#cb15-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-399"><a href="#cb15-399" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Fonction <span class="pp">|</span> Utilisation <span class="pp">|</span> Description <span class="pp">|</span></span>
<span id="cb15-400"><a href="#cb15-400" aria-hidden="true" tabindex="-1"></a><span class="pp">|----------|-------------|-------------|</span></span>
<span id="cb15-401"><a href="#cb15-401" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> <span class="in">`logc_so4`</span> en CL <span class="pp">|</span> $\log c_{\text{SO}_4}$ : monte de $-6$ à $-0.456$ (de $10^{-6}$ à $0.35\,\text{mol/L}$) en $10\,\text{jours}$ <span class="pp">|</span></span>
<span id="cb15-402"><a href="#cb15-402" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> <span class="in">`logc_k`</span> en CL <span class="pp">|</span> $\log c_K$ : monte de $-5.7$ à $-0.156$ (de $2\times10^{-6}$ à $0.7\,\text{mol/L}$) en $10\,\text{jours}$ <span class="pp">|</span></span>
<span id="cb15-403"><a href="#cb15-403" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> <span class="in">`z_al`</span> initial <span class="pp">|</span> Constante $= 1$ (aluminium solide stable) <span class="pp">|</span></span>
<span id="cb15-404"><a href="#cb15-404" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> <span class="in">`z_ca`</span> initial <span class="pp">|</span> Pente légère (dissolution lente de CH au cours du 1er jour) <span class="pp">|</span></span>
<span id="cb15-405"><a href="#cb15-405" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> <span class="in">`logc_oh`</span> en CL <span class="pp">|</span> pH constant à 12 ($c_{\text{OH}^-} = 10^{-2}\,\text{mol/L}$) <span class="pp">|</span></span>
<span id="cb15-406"><a href="#cb15-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-407"><a href="#cb15-407" aria-hidden="true" tabindex="-1"></a><span class="fu">### 8.7 Conditions aux limites (`Boundary Conditions`)</span></span>
<span id="cb15-408"><a href="#cb15-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-409"><a href="#cb15-409" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-410"><a href="#cb15-410" aria-hidden="true" tabindex="-1"></a><span class="in">Boundary Conditions</span></span>
<span id="cb15-411"><a href="#cb15-411" aria-hidden="true" tabindex="-1"></a><span class="in">4</span></span>
<span id="cb15-412"><a href="#cb15-412" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = logc_so4   Field = 1 Function = 1</span></span>
<span id="cb15-413"><a href="#cb15-413" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = psi        Field = 0 Function = 0</span></span>
<span id="cb15-414"><a href="#cb15-414" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = logc_k     Field = 1 Function = 2</span></span>
<span id="cb15-415"><a href="#cb15-415" aria-hidden="true" tabindex="-1"></a><span class="in">Region = 1 Unknown = logc_oh    Field = 1 Function = 5</span></span>
<span id="cb15-416"><a href="#cb15-416" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-417"><a href="#cb15-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-418"><a href="#cb15-418" aria-hidden="true" tabindex="-1"></a>Les conditions aux limites sont appliquées à la **région 1** (surface exposée $x=0$) :</span>
<span id="cb15-419"><a href="#cb15-419" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Les concentrations en sulfate et potassium sont **imposées** et augmentent au cours du temps (fonctions 1 et 2).</span>
<span id="cb15-420"><a href="#cb15-420" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Le potentiel électrique est maintenu à **zéro** (référence).</span>
<span id="cb15-421"><a href="#cb15-421" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Le pH est **maintenu à 12** tout au long de la simulation (fonction 5, constante).</span>
<span id="cb15-422"><a href="#cb15-422" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$z_\text{Ca}$ et $z_\text{Al}$ ne sont **pas prescrits** en CL (lignes commentées) : le calcium solide évolue librement par dissolution/précipitation.</span>
<span id="cb15-423"><a href="#cb15-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-424"><a href="#cb15-424" aria-hidden="true" tabindex="-1"></a><span class="fu">### 8.8 Points d'observation (`Points`)</span></span>
<span id="cb15-425"><a href="#cb15-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-426"><a href="#cb15-426" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-427"><a href="#cb15-427" aria-hidden="true" tabindex="-1"></a><span class="in">Points</span></span>
<span id="cb15-428"><a href="#cb15-428" aria-hidden="true" tabindex="-1"></a><span class="in">1</span></span>
<span id="cb15-429"><a href="#cb15-429" aria-hidden="true" tabindex="-1"></a><span class="in">0.5</span></span>
<span id="cb15-430"><a href="#cb15-430" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-431"><a href="#cb15-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-432"><a href="#cb15-432" aria-hidden="true" tabindex="-1"></a>Un seul point d'observation est défini, à $x = 0.5\,\text{dm}$ (centre de l'échantillon). C'est à ce point que les variables secondaires (colonnes du fichier <span class="in">`.p1`</span>) sont enregistrées au cours du temps.</span>
<span id="cb15-433"><a href="#cb15-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-434"><a href="#cb15-434" aria-hidden="true" tabindex="-1"></a><span class="fu">### 8.9 Fenêtre temporelle et critères de convergence</span></span>
<span id="cb15-435"><a href="#cb15-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-436"><a href="#cb15-436" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-437"><a href="#cb15-437" aria-hidden="true" tabindex="-1"></a><span class="in">Dates</span></span>
<span id="cb15-438"><a href="#cb15-438" aria-hidden="true" tabindex="-1"></a><span class="in">2</span></span>
<span id="cb15-439"><a href="#cb15-439" aria-hidden="true" tabindex="-1"></a><span class="in">0.  3.5e6       # t=0 s à t=3.5×10⁶ s ≈ 40 jours</span></span>
<span id="cb15-440"><a href="#cb15-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-441"><a href="#cb15-441" aria-hidden="true" tabindex="-1"></a><span class="in">Objective Variations</span></span>
<span id="cb15-442"><a href="#cb15-442" aria-hidden="true" tabindex="-1"></a><span class="in">logc_so4  = 1.e-3   # Variation relative tolérée pour l'inconnue sulfate</span></span>
<span id="cb15-443"><a href="#cb15-443" aria-hidden="true" tabindex="-1"></a><span class="in">z_ca      = 1.e-3</span></span>
<span id="cb15-444"><a href="#cb15-444" aria-hidden="true" tabindex="-1"></a><span class="in">psi       = 1.e-1</span></span>
<span id="cb15-445"><a href="#cb15-445" aria-hidden="true" tabindex="-1"></a><span class="in">logc_k    = 1.e-1</span></span>
<span id="cb15-446"><a href="#cb15-446" aria-hidden="true" tabindex="-1"></a><span class="in">z_al      = 1.e-1</span></span>
<span id="cb15-447"><a href="#cb15-447" aria-hidden="true" tabindex="-1"></a><span class="in">logc_oh   = 1.e-1</span></span>
<span id="cb15-448"><a href="#cb15-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-449"><a href="#cb15-449" aria-hidden="true" tabindex="-1"></a><span class="in">Iterative Process</span></span>
<span id="cb15-450"><a href="#cb15-450" aria-hidden="true" tabindex="-1"></a><span class="in">Iter = 20       # Nombre max d'itérations Newton-Raphson par pas de temps</span></span>
<span id="cb15-451"><a href="#cb15-451" aria-hidden="true" tabindex="-1"></a><span class="in">Tol  = 1.e-4    # Tolérance sur le résidu global</span></span>
<span id="cb15-452"><a href="#cb15-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-453"><a href="#cb15-453" aria-hidden="true" tabindex="-1"></a><span class="in">Time Steps</span></span>
<span id="cb15-454"><a href="#cb15-454" aria-hidden="true" tabindex="-1"></a><span class="in">Dtini = 1.e3    # Pas de temps initial : 1000 s ≈ 17 min</span></span>
<span id="cb15-455"><a href="#cb15-455" aria-hidden="true" tabindex="-1"></a><span class="in">Dtmax = 1.e3    # Pas de temps maximum : 1000 s (fixe)</span></span>
<span id="cb15-456"><a href="#cb15-456" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-457"><a href="#cb15-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-458"><a href="#cb15-458" aria-hidden="true" tabindex="-1"></a>Le pas de temps fixe de $1000\,\text{s}$ est adapté aux cinétiques chimiques les plus rapides (AFm, C₃AH₆ avec $R_x = 10^{-6}\,\text{mol/L/s}$). La tolérance <span class="in">`Objective Variations`</span> contrôle le pas de temps adaptatif de BIL : si la variation d'une inconnue dépasse son seuil, le pas est découpé.</span>
<span id="cb15-459"><a href="#cb15-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-460"><a href="#cb15-460" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb15-461"><a href="#cb15-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-462"><a href="#cb15-462" aria-hidden="true" tabindex="-1"></a><span class="fu">## 9. Références bibliographiques</span></span>
<span id="cb15-463"><a href="#cb15-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-464"><a href="#cb15-464" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Biot, M. A.** (1941). General theory of three-dimensional consolidation. *Journal of applied physics*, 12(2), 155–164. — Fonde le couplage pression interstitielle / déformation (coefficient de Biot $b = 0.54$ utilisé dans le modèle).</span>
<span id="cb15-465"><a href="#cb15-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-466"><a href="#cb15-466" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Coussy, O.** (2004). *Poromechanics*. John Wiley &amp; Sons. — Traitement rigoureux de la pression de cristallisation en milieu poreux (Eq. de Kelvin-Thomson appliquée aux cristaux en croissance dans les pores).</span>
<span id="cb15-467"><a href="#cb15-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-468"><a href="#cb15-468" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Flatt, R. J. &amp; Scherer, G. W.** (2008). Thermodynamics of crystallization stresses in DEF. *Cement and Concrete Research*, 38(3), 325–336. — Base thermodynamique du calcul de pression de cristallisation de l'ettringite différée $P_c = \frac{RT}{V_\text{AFt}}\ln\beta$.</span>
<span id="cb15-469"><a href="#cb15-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-470"><a href="#cb15-470" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Montoya, A. G., et al.** (2016). A chemo-mechanical model for sulfate attack in concrete — Fournit le cadre du couplage chimie-mécanique utilisé dans Sulfaco (endommagement, gonflement, altération de porosité).</span>
<span id="cb15-471"><a href="#cb15-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-472"><a href="#cb15-472" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Nernst, W. &amp; Planck, M.** (1890). Théorie de diffusion ionique couplée au potentiel électrique. — Équation de Nernst-Planck pour le transport d'ions en solution poreuse ($\mathbf{W}_i = -\phi\tau(D_i \nabla c_i + z_i \frac{FD_i}{RT} c_i \nabla\psi)$).</span>
<span id="cb15-473"><a href="#cb15-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-474"><a href="#cb15-474" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Bazant, Z. P. &amp; Najjar, L. J.** (1972). Nonlinear water diffusion in nonsaturated concrete. *Matériaux et Construction*, 5(25), 3–20. — Loi de tortuosité $\tau(\phi)$ utilisée dans le calcul des flux diffusifs.</span>
<span id="cb15-475"><a href="#cb15-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-476"><a href="#cb15-476" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Van Genuchten, M. Th.** (1980). A closed-form equation for predicting the hydraulic conductivity of unsaturated soils. *Soil Science Society of America Journal*, 44(5), 892–898. — Modèle de courbe de saturation $S_r(r)$ utilisé pour la distribution de rayons de pores (paramètres $m=0.2516$, $r_0 = 155.82\,\text{nm}$).</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Bil — Bibliothèque d’Ingénierie numérique et de Lois de comportement</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dangla/bil/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Généré avec <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>